import type { Level } from '../types.js'

// Premium world #1: Area 51 / UFO lore. 10 levels selected for the canonical
// UFO journey — the most iconic themes (ALIEN, SAUCER, ROSWELL, ABDUCTION,
// MOTHERSHIP) carry the marquee experience while preserving a smooth
// difficulty crescendo from 3.5 → 13.0 across the full 5 → 10-letter arc.
// The 10 secondary themes that originally lived here have moved to the
// 'area515' weekly event (see area515Levels.ts) so they still see play in
// the rotation without diluting the premium dossier.
// Every word has been hand-validated against its letter pool (canMakeWord).

export const AREA51_LEVELS: Level[] = [
  {
    theme: 'ALIEN', difficulty: 3.5,
    letters: ['A','L','I','E','N'],
    words: ['ALIEN','LINEA','ELAN','LAIN','LEAN','LIEN','LINE','NAIL','AIL','AIN'], bonus: ['ANIL'],
    defs: {
      ALIEN: 'A being from another world — the central subject of Area 51 lore',
      LINEA: 'A medical term for a line or stripe on the body',
      ELAN: 'Vigorous spirit or enthusiasm',
      LAIN: 'Past participle of lie',
      LEAN: 'To incline; thin',
      LIEN: 'A legal claim on property',
      LINE: 'A long narrow mark',
      NAIL: 'A fastener; a fingernail',
      AIL: 'To trouble or be unwell',
      AIN: 'Own (Scottish)',
      ANIL: 'A West Indian shrub yielding indigo',
    }
  },
  {
    theme: 'PROBE', difficulty: 4.0,
    letters: ['P','R','O','B','E'],
    words: ['PROBE','BORE','PORE','ROBE','ROPE','BOP','BRO','OBE','OPE','ORB','PER'], bonus: ['REPO'],
    defs: {
      PROBE: 'A scientific or extraterrestrial investigative device',
      BORE: 'To drill; a dull person',
      PORE: 'A tiny opening; to study intently',
      ROBE: 'A long flowing garment',
      ROPE: 'A thick cord',
      BOP: 'A jazz style; to strike lightly',
      BRO: 'Brother (informal)',
      OBE: 'Order of the British Empire honor',
      OPE: 'To open (poetic)',
      ORB: 'A sphere',
      PER: 'For each',
      REPO: 'A repossession',
    }
  },
  {
    theme: 'AGENT', difficulty: 4.7,
    letters: ['A','G','E','N','T'],
    words: ['AGENT','ANTE','GATE','GENT','GNAT','NEAT','TANG','AGE','ANT','ATE','EAT','ETA','GAN'], bonus: ['EGAN'],
    defs: {
      AGENT: 'A field operative — Men in Black, FBI, or anyone whose clearance you can\'t see',
      ANTE: 'A poker stake; to pay in',
      GATE: 'An entry point',
      GENT: 'A gentleman',
      GNAT: 'A small biting fly',
      NEAT: 'Tidy; pleasingly simple',
      TANG: 'A sharp taste',
      AGE: 'A period of time',
      ANT: 'A small social insect',
      ATE: 'Past tense of eat',
      EAT: 'To consume food',
      ETA: 'Greek letter; estimated time of arrival',
      GAN: 'Past tense of gin (archaic)',
      EGAN: 'A surname; archaic past of egg',
    }
  },
  {
    theme: 'SAUCER', difficulty: 5.5,
    letters: ['S','A','U','C','E','R'],
    words: ['SAUCER','CARES','CAUSE','CRUSE','CURSE','RACES','SAUCE','ACES','ACRE','ARCS','ARES','CARE','CARS'], bonus: ['CRUES'],
    defs: {
      SAUCER: 'A flying disc — the classic UFO silhouette since the 1947 Roswell incident',
      CARES: 'Worries; tends to',
      CAUSE: 'A reason; to bring about',
      CRUSE: 'A small earthen vessel for liquids',
      CURSE: 'A solemn malediction',
      RACES: 'Competitions of speed',
      SAUCE: 'A liquid condiment',
      ACES: 'Top performers; playing cards',
      ACRE: 'A unit of land area',
      ARCS: 'Curved paths',
      ARES: 'Plural of are; a Greek war god',
      CARE: 'Concern; to look after',
      CARS: 'Motor vehicles',
      CRUES: 'Variant plural of cru (a vineyard)',
    }
  },
  {
    theme: 'HANGAR', difficulty: 6.5,
    letters: ['H','A','N','G','A','R'],
    words: ['HANGAR','GRANA','AGAR','AGHA','GNAR','GRAN','HANG','NAGA','AAH','AGA','AHA','GAR','HAG','NAG','NAH'], bonus: ['RANGA'],
    defs: {
      HANGAR: 'A building for housing aircraft — Hangar 18 supposedly hides recovered craft',
      GRANA: 'Plural of granum; chloroplast structure',
      AGAR: 'A gelatin used in lab cultures',
      AGHA: 'A Turkish military or civil officer',
      GNAR: 'To snarl or growl',
      GRAN: 'Grandmother (informal)',
      HANG: 'To suspend',
      NAGA: 'A serpent deity in Hindu and Buddhist lore',
      AAH: 'An exclamation of comprehension',
      AGA: 'A title for high-ranking officers in the Ottoman Empire',
      AHA: 'Exclamation of discovery',
      GAR: 'A long needle-toothed fish',
      HAG: 'An ugly old woman',
      NAG: 'To pester',
      NAH: 'Informal "no"',
      RANGA: 'A redhead (Australian slang)',
    }
  },
  {
    theme: 'ROSWELL', difficulty: 8.0,
    letters: ['R','O','S','W','E','L','L'],
    words: ['ROSWELL','LOWERS','ROWELS','LORES','LOWER','ROLES','ROWEL','SOWER','SWORE','WORSE','ELLS','LOSE','LOWE','OWES','OWLS','ROES','ROLE','ROLL'], bonus: ['SLOWER'],
    defs: {
      ROSWELL: 'A 1947 incident in New Mexico — the alleged crash that started it all',
      LOWERS: 'Decreases; descends',
      ROWELS: 'Spiked wheels of a spur',
      LORES: 'Bodies of traditional knowledge',
      LOWER: 'Less high; to drop',
      ROLES: 'Functions or parts played',
      ROWEL: 'The spiked wheel of a spur',
      SOWER: 'One who sows seed',
      SWORE: 'Past tense of swear',
      WORSE: 'Of inferior quality',
      ELLS: 'Plural of ell; an old unit of length',
      LOSE: 'To be deprived of',
      LOWE: 'A flame (Scottish dialect)',
      OWES: 'Is in debt to',
      OWLS: 'Plural of owl',
      ROES: 'Fish eggs',
      ROLE: 'A part played',
      ROLL: 'To revolve; a bread roll',
      SLOWER: 'Less fast',
    }
  },
  {
    theme: 'CONTACT', difficulty: 8.5,
    letters: ['C','O','N','T','A','C','T'],
    words: ['CONTACT','CANTO','COTAN','OCTAN','CANT','COAT','COCA','TACO','TACT','ACT','ANT','CAN','CAT','COT','CON','NOT','OAT','OCA','TAN'], bonus: ['OCTANT'],
    defs: {
      CONTACT: 'First confirmed communication with extraterrestrial intelligence',
      CANTO: 'A section of a long poem',
      COTAN: 'Cotangent (math)',
      OCTAN: 'A fever recurring every eighth day',
      CANT: 'A tilt; specialized jargon',
      COAT: 'An outer garment',
      COCA: 'A shrub whose leaves yield cocaine',
      TACO: 'A folded tortilla dish',
      TACT: 'Sensitivity in dealing with others',
      ACT: 'A deed',
      ANT: 'A social insect',
      CAN: 'A metal container',
      CAT: 'A small carnivorous mammal',
      COT: 'A small portable bed',
      CON: 'A swindle; against',
      NOT: 'Negation',
      OAT: 'A grain crop',
      OCA: 'A South American wood sorrel',
      TAN: 'A light brown color',
      OCTANT: 'A navigation instrument; one-eighth of a circle',
    }
  },
  {
    theme: 'STARSHIP', difficulty: 9.5,
    letters: ['S','T','A','R','S','H','I','P'],
    words: ['STARSHIP','HARPIST','PARISH','RAPIST','SPRATS','STAIRS','STRAPS','AIRTS','APHIS','ATRIP','HARPS','HARTS','PARTS','PATHS','HAIR','HARP','HATS','HIPS','PAIR','PARS'], bonus: ['STIRPS'],
    defs: {
      STARSHIP: 'An interstellar vessel — capable of crossing the gulf between worlds',
      HARPIST: 'A harp player',
      PARISH: 'A church district',
      RAPIST: 'A sexual offender',
      SPRATS: 'Small herring-like fish',
      STAIRS: 'Steps leading up or down',
      STRAPS: 'Bands of leather or fabric',
      AIRTS: 'Directions; courses (Scottish)',
      APHIS: 'A plant louse',
      ATRIP: 'Just clear of the bottom (of an anchor)',
      HARPS: 'Stringed instruments',
      HARTS: 'Male deer',
      PARTS: 'Sections',
      PATHS: 'Tracks for walking',
      HAIR: 'A filament from the scalp',
      HARP: 'A stringed instrument',
      HATS: 'Head coverings',
      HIPS: 'Body joints between waist and thigh',
      PAIR: 'Two of a kind',
      PARS: 'Standards in golf',
      STIRPS: 'A line of descent (bonus)',
    }
  },
  {
    theme: 'ABDUCTION', difficulty: 11.5,
    letters: ['A','B','D','U','C','T','I','O','N'],
    words: ['ABDUCTION','ABDUCT','BANDIT','DACOIT','OUTBID','ACTIN','ACTON','AUDIO','AUDIT','BANCO','BIDON','CUBIT','DUCAT','INCUT','TONIC','OCTAD','UNCIA','ABUT','ACID','AUTO'], bonus: ['OBTAIN'],
    defs: {
      ABDUCTION: 'The reported act of being taken aboard a craft — a recurring theme in contact lore',
      ABDUCT: 'To take away by force',
      BANDIT: 'A robber',
      DACOIT: 'An Indian or Burmese armed robber',
      OUTBID: 'To bid higher than another',
      ACTIN: 'A protein in muscle cells',
      ACTON: 'A quilted jacket worn under armor',
      AUDIO: 'Related to sound',
      AUDIT: 'A formal review',
      BANCO: 'A betting term in baccarat',
      BIDON: 'A metal canister for liquids',
      CUBIT: 'An ancient unit of length',
      DUCAT: 'A gold coin of historic Europe',
      INCUT: 'Notched inward',
      TONIC: 'Giving a feeling of vigor; a refreshing drink',
      OCTAD: 'A group of eight',
      UNCIA: 'A twelfth (Roman fraction)',
      ABUT: 'To border or touch',
      ACID: 'A sour chemical compound',
      AUTO: 'An automobile',
      OBTAIN: 'To acquire; to come into possession of',
    }
  },
  {
    theme: 'MOTHERSHIP', difficulty: 13.0,
    letters: ['M','O','T','H','E','R','S','H','I','P'],
    words: ['MOTHERSHIP','ISOTHERM','TROPHIES','HEROISM','HOMIEST','SMOTHER','HERMIT','MIRTHS','MISTER','POSHER','POTHER','THORPE','TROPES','HORSE','HORST','METRO','MOIRE','OTHER','SHORE','SHORT'], bonus: ['THERMS'],
    defs: {
      MOTHERSHIP: 'The largest craft in a UFO fleet — said to carry smaller scouts inside',
      ISOTHERM: 'A line on a map joining points of equal temperature',
      TROPHIES: 'Awards for victory',
      HEROISM: 'Great bravery',
      HOMIEST: 'Most homelike',
      SMOTHER: 'To suffocate',
      HERMIT: 'A solitary recluse',
      MIRTHS: 'Joyful amusements',
      MISTER: 'A title for a man',
      POSHER: 'More posh',
      POTHER: 'Commotion; fuss',
      THORPE: 'A small village (archaic)',
      TROPES: 'Figures of speech',
      HORSE: 'A large hoofed animal',
      HORST: 'A raised block of the earth\'s crust',
      METRO: 'An underground rail system',
      MOIRE: 'A watered or wavelike pattern',
      OTHER: 'Different from the one mentioned',
      SHORE: 'The land along an ocean or lake',
      SHORT: 'Of little length',
      THERMS: 'Units of heat (bonus)',
    }
  },
]
