import type { Level } from '../types.js'

// Premium world #2: Asimov Robotics. 20 levels, theme-length crescendo
// 5 → 10 letters, every theme flavored after I,Robot / Foundation / Three Laws.
// Every word hand-validated against its letter pool (canMakeWord).

export const ASIMOV_LEVELS: Level[] = [
  {
    theme: 'ROBOT', difficulty: 3.5,
    letters: ['R','O','B','O','T'],
    words: ['ROBOT','BOOT','BORT','ROOT','TORO','BOO','BOT','BRO','ORB','ROB'], bonus: ['ROTO'],
    defs: {
      ROBOT: 'In Asimov\'s universe, a positronic-brained mechanical being bound by the Three Laws',
      BOOT: 'A type of footwear; to start a computer',
      BORT: 'Industrial-grade diamond fragments',
      ROOT: 'The underground part of a plant; the base of a thing',
      TORO: 'A bull (Spanish/Italian)',
      BOO: 'A shout of disapproval',
      BOT: 'A software robot',
      BRO: 'Brother (informal)',
      ORB: 'A sphere',
      ROB: 'To take by force',
      ROTO: 'Rotogravure printing',
    }
  },
  {
    theme: 'LOGIC', difficulty: 3.8,
    letters: ['L','O','G','I','C'],
    words: ['LOGIC','CLOG','COIL','COLI','LOCI','COG','COL','LOG','OIL'], bonus: [],
    defs: {
      LOGIC: 'The branch of math/philosophy that drives every Asimov robot\'s reasoning',
      CLOG: 'To block; a wooden shoe',
      COIL: 'A spiral of wire',
      COLI: 'A genus of bacteria (E. coli)',
      LOCI: 'Plural of locus; points in space',
      COG: 'A toothed gear; a minor employee',
      COL: 'A mountain pass',
      LOG: 'A piece of timber; a record',
      OIL: 'A viscous liquid lubricant',
    }
  },
  {
    theme: 'BRAIN', difficulty: 4.0,
    letters: ['B','R','A','I','N'],
    words: ['BRAIN','BAIRN','BARN','BRAN','RAIN','RANI','AIR','AIN','BAN','BAR','BIN'], bonus: [],
    defs: {
      BRAIN: 'In Asimov stories, the positronic brain makes a robot self-aware',
      BAIRN: 'A child (Scottish)',
      BARN: 'A large farm building',
      BRAN: 'The outer husk of grain',
      RAIN: 'Water droplets falling from the sky',
      RANI: 'An Indian queen',
      AIR: 'The atmosphere',
      AIN: 'Own (Scottish)',
      BAN: 'To prohibit',
      BAR: 'A rod; a drinking establishment',
      BIN: 'A storage container',
    }
  },
  {
    theme: 'LASER', difficulty: 4.3,
    letters: ['L','A','S','E','R'],
    words: ['LASER','EARLS','RALES','REALS','SERAL','ALES','ARES','EARL','EARS','ERAS','RALE','SALE'], bonus: ['ARSE'],
    defs: {
      LASER: 'Light Amplification by Stimulated Emission of Radiation — staple sci-fi armament',
      EARLS: 'British noblemen',
      RALES: 'Abnormal rattling sounds heard in the lungs',
      REALS: 'Brazilian currency units',
      SERAL: 'Relating to an ecological sere',
      ALES: 'Plural of ale',
      ARES: 'Plural of are; a Greek war god',
      EARL: 'A British nobleman',
      EARS: 'Plural of ear',
      ERAS: 'Plural of era',
      RALE: 'A lung sound',
      SALE: 'An offer for purchase',
      ARSE: 'Buttocks (British vulgar)',
    }
  },
  {
    theme: 'METAL', difficulty: 4.7,
    letters: ['M','E','T','A','L'],
    words: ['METAL','LAME','LATE','MALE','MALT','MATE','MEAL','MEAT','MELT','TALE','TAME','TEAL','TEAM'], bonus: [],
    defs: {
      METAL: 'The substance most Asimov robots are clad in — typically a chrome-steel alloy',
      LAME: 'Unable to walk properly; weak',
      LATE: 'After the expected time',
      MALE: 'Of the masculine sex',
      MALT: 'Germinated grain used in brewing',
      MATE: 'A companion',
      MEAL: 'Food eaten at one sitting',
      MEAT: 'Animal flesh as food',
      MELT: 'To turn from solid to liquid',
      TALE: 'A story',
      TAME: 'Not wild',
      TEAL: 'A blue-green color',
      TEAM: 'A group working together',
    }
  },
  {
    theme: 'SENSOR', difficulty: 5.5,
    letters: ['S','E','N','S','O','R'],
    words: ['SENSOR','SNORES','NOSES','ROSES','SNORE','SONES','SORES','EROS','NOES','NOSE','ONES','ORES','ROES'], bonus: ['SORE'],
    defs: {
      SENSOR: 'A device for detecting input — robots use optical, audio, and tactile sensors',
      SNORES: 'Plural of snore',
      NOSES: 'Plural of nose',
      ROSES: 'Plural of rose',
      SNORE: 'To breathe noisily while asleep',
      SONES: 'Units of perceived loudness',
      SORES: 'Plural of sore',
      EROS: 'Sexual love personified',
      NOES: 'Plural of no',
      NOSE: 'The organ of smell',
      ONES: 'Plural of one',
      ORES: 'Rocks containing valuable minerals',
      ROES: 'Fish eggs',
      SORE: 'A painful wound or feeling',
    }
  },
  {
    theme: 'BINARY', difficulty: 6.0,
    letters: ['B','I','N','A','R','Y'],
    words: ['BINARY','BRAINY','BAIRN','BRAIN','RAINY','AIRY','BARN','BRAN','BRAY','NARY','RAIN','RANI','YARN','BAR'], bonus: ['ABRI'],
    defs: {
      BINARY: 'Base-2 numeric system — the underlying language of every digital computation',
      BRAINY: 'Intelligent',
      BAIRN: 'A child (Scottish)',
      BRAIN: 'The organ of thought',
      RAINY: 'Marked by rain',
      AIRY: 'Open to the air; light',
      BARN: 'A large farm building',
      BRAN: 'The outer husk of grain',
      BRAY: 'The sound of a donkey',
      NARY: 'Not any (archaic)',
      RAIN: 'Precipitation',
      RANI: 'An Indian queen',
      YARN: 'Spun thread; a long story',
      BAR: 'A rod',
      ABRI: 'A shelter (French, accepted in some dictionaries)',
    }
  },
  {
    theme: 'SIGNAL', difficulty: 6.5,
    letters: ['S','I','G','N','A','L'],
    words: ['SIGNAL','ALIGNS','GAINS','NAILS','SLAIN','SLING','SNAIL','AILS','ANIS','GAIN','GALS','NAGS','NAIL','SAIL'], bonus: ['LINGAS'],
    defs: {
      SIGNAL: 'A transmitted message — Foundation\'s galactic empire relied on signals',
      ALIGNS: 'Brings into line',
      GAINS: 'Increases; profits',
      NAILS: 'Fasteners; fingernails',
      SLAIN: 'Past participle of slay',
      SLING: 'A strap for hurling stones',
      SNAIL: 'A slow gastropod',
      AILS: 'Troubles',
      ANIS: 'Plural of ani; tropical birds',
      GAIN: 'To acquire',
      GALS: 'Girls (informal)',
      NAGS: 'Pesters',
      NAIL: 'A fastener; a fingernail',
      SAIL: 'A sheet of fabric for wind propulsion',
      LINGAS: 'Plural of linga; phallic Hindu emblems',
    }
  },
  {
    theme: 'ROBOTS', difficulty: 7.0,
    letters: ['R','O','B','O','T','S'],
    words: ['ROBOTS','BOORS','BOOST','BOOTS','ROBOT','ROOTS','TOROS','BOOR','BOOS','BOOT','BROS','ROBS','ROOT','TORO','TORS'], bonus: ['BORTS'],
    defs: {
      ROBOTS: 'Asimov\'s 1950 collection I, Robot defined the genre — bound by the Three Laws',
      BOORS: 'Plural of boor; rude people',
      BOOST: 'To raise up',
      BOOTS: 'Plural of boot',
      ROBOT: 'A positronic-brained mechanical being',
      ROOTS: 'Underground parts of plants',
      TOROS: 'Plural of toro; bulls',
      BOOR: 'A rude person',
      BOOS: 'Shouts of disapproval',
      BOOT: 'A type of footwear',
      BROS: 'Brothers',
      ROBS: 'Takes by force',
      ROOT: 'The base of a plant',
      TORO: 'A bull (Spanish/Italian)',
      TORS: 'Rocky peaks',
      BORTS: 'Diamond fragments',
    }
  },
  {
    theme: 'MATRIX', difficulty: 7.5,
    letters: ['M','A','T','R','I','X'],
    words: ['MATRIX','AMIR','MAIR','MART','TRAM','TRIM','AIM','AIR','AIT','ARM','ART','MAR','MAT','MIR','RAT','RIM','TAR'], bonus: [],
    defs: {
      MATRIX: 'A rectangular array of values; the core data structure of neural networks',
      AMIR: 'A Muslim ruler (variant of emir)',
      MAIR: 'More (Scottish)',
      MART: 'A market',
      TRAM: 'A streetcar',
      TRIM: 'To cut neatly',
      AIM: 'To direct',
      AIR: 'The atmosphere',
      AIT: 'A small island in a river',
      ARM: 'A limb; to equip',
      ART: 'Creative expression',
      MAR: 'To spoil',
      MAT: 'A floor covering',
      MIR: 'A Russian peasant assembly',
      RAT: 'A rodent; a traitor',
      RIM: 'The outer edge',
      TAR: 'A dark sticky liquid',
    }
  },
  {
    theme: 'ANDROID', difficulty: 8.0,
    letters: ['A','N','D','R','O','I','D'],
    words: ['ANDROID','INROAD','ADORN','AROID','DINAR','DRAIN','NADIR','RADIO','RADON','ARID','DARN','DINO','IRON','NARD','RAID','ROAD','ADO','AID'], bonus: [],
    defs: {
      ANDROID: 'A robot built to resemble a human — Daneel Olivaw is Asimov\'s most famous android',
      INROAD: 'A hostile incursion; progress made',
      ADORN: 'To decorate',
      AROID: 'Belonging to the arum family of plants',
      DINAR: 'A monetary unit of several Middle Eastern countries',
      DRAIN: 'A channel for liquid',
      NADIR: 'The lowest point',
      RADIO: 'A wireless communication device',
      RADON: 'A radioactive noble gas',
      ARID: 'Very dry',
      DARN: 'To mend with thread',
      DINO: 'A dinosaur (informal)',
      IRON: 'A metallic element',
      NARD: 'A fragrant Old World plant',
      RAID: 'A sudden assault',
      ROAD: 'A traveled path',
      ADO: 'A fuss',
      AID: 'Help',
    }
  },
  {
    theme: 'COMPUTE', difficulty: 8.5,
    letters: ['C','O','M','P','U','T','E'],
    words: ['COMPUTE','COMET','COMTE','COUPE','COMP','COPE','COTE','COUP','CUTE','MOPE','MOTE','MUTE','POEM','POET','PUCE','TOME','CEP','CUE','CUP'], bonus: [],
    defs: {
      COMPUTE: 'To calculate; the foundational task of every Asimov machine intelligence',
      COMET: 'A celestial body with a tail',
      COMTE: 'A count (French nobility)',
      COUPE: 'A two-door car',
      COMP: 'A complimentary item',
      COPE: 'To deal with difficulty',
      COTE: 'A small shed for birds',
      COUP: 'A sudden decisive act',
      CUTE: 'Charming',
      MOPE: 'To be dejected',
      MOTE: 'A speck of dust',
      MUTE: 'Silent',
      POEM: 'A composition in verse',
      POET: 'A writer of poems',
      PUCE: 'A brownish purple color',
      TOME: 'A large book',
      CEP: 'A type of mushroom',
      CUE: 'A signal',
      CUP: 'A drinking vessel',
    }
  },
  {
    theme: 'PROGRAM', difficulty: 9.0,
    letters: ['P','R','O','G','R','A','M'],
    words: ['PROGRAM','ARMOR','GRAM','PRAM','PROA','PROG','ROAR','AMP','ARM','GAP','GAR','GOA','MAG','MAR','OAR','PAR','PRO','RAG','RAM','RAP'], bonus: [],
    defs: {
      PROGRAM: 'A set of instructions; Susan Calvin programmed robot psychology in Asimov\'s stories',
      ARMOR: 'Defensive metallic covering',
      GRAM: 'A unit of mass',
      PRAM: 'A baby carriage',
      PROA: 'A swift Malayan sailing boat',
      PROG: 'To search for food (slang)',
      ROAR: 'A deep loud cry',
      AMP: 'An ampere',
      ARM: 'A limb',
      GAP: 'An opening',
      GAR: 'A long-snouted fish',
      GOA: 'A Tibetan gazelle',
      MAG: 'A magazine',
      MAR: 'To spoil',
      OAR: 'A pole for rowing',
      PAR: 'A standard',
      PRO: 'A professional',
      RAG: 'A torn piece of cloth',
      RAM: 'A male sheep',
      RAP: 'To strike sharply',
    }
  },
  {
    theme: 'POSITRON', difficulty: 9.5,
    letters: ['P','O','S','I','T','R','O','N'],
    words: ['POSITRON','PORTION','PROTONS','POINTS','PRIONS','TROOPS','INTRO','IRONS','PINOT','POINT','PORTS','POSIT','PRINT','PRION','PROTO','INTO','IONS','IRON','OOPS','OPTS'], bonus: [],
    defs: {
      POSITRON: 'A positively-charged electron — Asimov coined "positronic brain" decades before such matter was even predicted',
      PORTION: 'A part of a whole',
      PROTONS: 'Positively-charged subatomic particles',
      POINTS: 'Sharp ends; scores',
      PRIONS: 'Misfolded protein particles',
      TROOPS: 'Bodies of soldiers',
      INTRO: 'An introduction',
      IRONS: 'Plural of iron',
      PINOT: 'A type of wine grape',
      POINT: 'A sharp end; a particular spot',
      PORTS: 'Plural of port; harbors',
      POSIT: 'To put forward as fact',
      PRINT: 'To produce a printed copy',
      PRION: 'A misfolded infectious protein',
      PROTO: 'First in time; original',
      INTO: 'Toward the interior of',
      IONS: 'Electrically charged atoms',
      IRON: 'A metallic element',
      OOPS: 'Exclamation of mild dismay',
      OPTS: 'Chooses',
    }
  },
  {
    theme: 'TERMINAL', difficulty: 10.0,
    letters: ['T','E','R','M','I','N','A','L'],
    words: ['TERMINAL','LATRINE','MINARET','ANTLER','LAMENT','MARTEN','MENIAL','RENTAL','RETAIL','RETINA','ALERT','ALIEN','ALTER','INERT','INTER','IRATE','LATER','LEARN','MATER','MATIN'], bonus: ['MARLINE'],
    defs: {
      TERMINAL: 'A computer interface; the readable end of every Asimov machine',
      LATRINE: 'A communal toilet',
      MINARET: 'A slender tower of a mosque',
      ANTLER: 'A branched bony horn',
      LAMENT: 'A mournful expression',
      MARTEN: 'A small carnivorous mammal',
      MENIAL: 'Lowly; humble',
      RENTAL: 'Something rented',
      RETAIL: 'Selling goods to consumers',
      RETINA: 'The light-sensitive layer of the eye',
      ALERT: 'Watchful',
      ALIEN: 'A foreigner; a being from another world',
      ALTER: 'To change',
      INERT: 'Lacking power to move',
      INTER: 'To bury',
      IRATE: 'Angry',
      LATER: 'Afterwards',
      LEARN: 'To acquire knowledge',
      MATER: 'Mother (Latin)',
      MATIN: 'A morning song (poetic)',
      MARLINE: 'A small line for fastening (nautical)',
    }
  },
  {
    theme: 'HARDWARE', difficulty: 10.5,
    letters: ['H','A','R','D','W','A','R','E'],
    words: ['HARDWARE','HARDER','REWARD','AHEAD','AWARD','AWARE','HAWED','HEARD','WADER','HARD','HARE','HEAR','HERD','READ','REAR','WADE','WARD','WARE','WEAR','DEAR'], bonus: ['WHARE'],
    defs: {
      HARDWARE: 'The physical electronics; robots are 100% hardware with software souls',
      HARDER: 'More difficult',
      REWARD: 'Something given in recognition',
      AHEAD: 'In front',
      AWARD: 'To grant; a prize',
      AWARE: 'Knowing',
      HAWED: 'Hesitated in speech',
      HEARD: 'Past tense of hear',
      WADER: 'One who wades',
      HARD: 'Solid; difficult',
      HARE: 'A fast-running rabbit-like animal',
      HEAR: 'To perceive sound',
      HERD: 'A group of animals',
      READ: 'To interpret writing',
      REAR: 'The back of something',
      WADE: 'To walk through water',
      WARD: 'A guarded area',
      WARE: 'Manufactured goods',
      WEAR: 'To carry on the body',
      DEAR: 'Beloved',
      WHARE: 'A Maori dwelling (bonus)',
    }
  },
  {
    theme: 'HUMANOID', difficulty: 11.0,
    letters: ['H','U','M','A','N','O','I','D'],
    words: ['HUMANOID','DAIMON','AMINO','AUDIO','HOUND','HUMID','HUMAN','MAUND','MONAD','MOUND','NOMAD','AMID','DAMN','DUMA','HAND','MAID','MAIN','MAUD','MIND','MOAN'], bonus: ['AMIDO'],
    defs: {
      HUMANOID: 'Having human form — most Asimov robots are humanoid to ease integration',
      DAIMON: 'A guardian spirit (Greek, variant of daemon)',
      AMINO: 'Of amino acids',
      AUDIO: 'Related to sound',
      HOUND: 'A hunting dog',
      HUMID: 'Marked by moisture',
      HUMAN: 'A member of Homo sapiens',
      MAUND: 'A unit of weight (South Asian)',
      MONAD: 'A simple unit; a single celled organism',
      MOUND: 'A raised heap of earth',
      NOMAD: 'A wanderer with no fixed home',
      AMID: 'In the middle of',
      DAMN: 'To condemn',
      DUMA: 'A Russian council',
      HAND: 'The end of the arm',
      MAID: 'A young unmarried woman',
      MAIN: 'Principal',
      MAUD: 'A Scottish striped plaid',
      MIND: 'The intellect',
      MOAN: 'A low sound of pain',
      AMIDO: 'Containing the amido group (chemistry)',
    }
  },
  {
    theme: 'DIRECTIVE', difficulty: 11.5,
    letters: ['D','I','R','E','C','T','I','V','E'],
    words: ['DIRECTIVE','EVICTED','RECITED','DEICER','DIRECT','RECITE','CITED','CRIED','DRIVE','EDICT','ERECT','ICIER','TIRED','TRICE','VIRID','CEDI','CIRE','CITE','DICE','DIRE'], bonus: [],
    defs: {
      DIRECTIVE: 'An order; Asimov\'s Three Laws are directives baked into every positronic brain',
      EVICTED: 'Forced out of a property',
      RECITED: 'Said aloud from memory',
      DEICER: 'A substance that melts ice',
      DIRECT: 'Straight; to guide',
      RECITE: 'To say aloud from memory',
      CITED: 'Quoted as an authority',
      CRIED: 'Wept',
      DRIVE: 'To operate a vehicle',
      EDICT: 'An official decree',
      ERECT: 'Upright; to build',
      ICIER: 'More icy',
      TIRED: 'Fatigued',
      TRICE: 'A very short time',
      VIRID: 'Green',
      CEDI: 'The currency of Ghana',
      CIRE: 'A glazed fabric finish',
      CITE: 'To quote as authority',
      DICE: 'Small cubes used in games',
      DIRE: 'Extremely serious',
    }
  },
  {
    theme: 'SYNTHETIC', difficulty: 12.0,
    letters: ['S','Y','N','T','H','E','T','I','C'],
    words: ['SYNTHETIC','INSECT','INCEST','ITCHES','NICEST','NICETY','STENCH','STITCH','TENTHS','ETHICS','ETHIC','HEIST','INSET','ITCHY','NICHE','SCENT','SHINE','SHINY','SYNTH','THEIST'], bonus: ['CHESTY'],
    defs: {
      SYNTHETIC: 'Artificially created — in Asimov\'s universe, synthetic life raises every moral question',
      INSECT: 'A small invertebrate animal',
      INCEST: 'Sexual relations between close relatives',
      ITCHES: 'Causes scratching',
      NICEST: 'Most agreeable',
      NICETY: 'A fine detail',
      STENCH: 'A strong unpleasant smell',
      STITCH: 'A loop of thread; a sharp pain',
      TENTHS: 'Plural of tenth',
      ETHICS: 'Moral principles',
      ETHIC: 'A set of moral principles',
      HEIST: 'A robbery',
      INSET: 'A small thing set into another',
      ITCHY: 'Causing an itch',
      NICHE: 'A specialized role',
      SCENT: 'A distinctive smell',
      SHINE: 'To emit light',
      SHINY: 'Reflecting light',
      SYNTH: 'A synthesizer',
      THEIST: 'A believer in God',
      CHESTY: 'Aggressively self-assertive',
    }
  },
  {
    theme: 'POSITRONIC', difficulty: 13.0,
    letters: ['P','O','S','I','T','R','O','N','I','C'],
    words: ['POSITRONIC','POSITION','POSITRON','COITION','PORTION','PROTONS','TROPICS','POINTS','PRINTS','PRIONS','TRIPOS','TROPIC','NOSTOC','ICONS','IRONS','NITRO','POINT','PORTS','POSIT','PRINT'], bonus: ['IRONIC'],
    defs: {
      POSITRONIC: 'The hallmark of Asimov\'s robots — a positron-based artificial brain that hosts the Three Laws',
      POSITION: 'A particular place',
      POSITRON: 'A positively-charged electron',
      COITION: 'Sexual union',
      PORTION: 'A part of a whole',
      PROTONS: 'Positively-charged subatomic particles',
      TROPICS: 'The hot regions near the equator',
      POINTS: 'Sharp ends; scores',
      PRINTS: 'Produces printed copies',
      PRIONS: 'Misfolded infectious proteins',
      TRIPOS: 'A Cambridge honors exam',
      TROPIC: 'Of the tropics',
      NOSTOC: 'A genus of cyanobacteria',
      ICONS: 'Pictorial symbols',
      IRONS: 'Plural of iron',
      NITRO: 'Short for nitroglycerin',
      POINT: 'A sharp end',
      PORTS: 'Harbors',
      POSIT: 'To put forward as fact',
      PRINT: 'To produce a printed copy',
      IRONIC: 'Marked by irony (bonus)',
    }
  },
]
