import type { Level } from '../types.js'

export const ETERNALNIGHT_LEVELS: Level[] = [
  {
    theme: 'NIGHT', difficulty: 3.2,
    letters: ['N','I','G','H','T'],
    words: ['NIGHT','HINT','NIGH','THIN','GIN','HIT','NIT','NTH','TIN'], bonus: [],
    defs: {
      NIGHT: 'In Mirandus Eternal Night, the night is a persistent threat — visibility falls, predators rise, and the cosmic hunt begins',
      HINT: 'A subtle clue',
      NIGH: 'Near in time or place',
      THIN: 'Of little thickness',
      GIN: 'A spirit; a trap',
      HIT: 'A successful strike',
      NIT: 'A louse egg; a trifling complaint',
      NTH: 'The last of an indefinite series',
      TIN: 'A soft silvery metal',
    }
  },
  {
    theme: 'HAUNT', difficulty: 3.5,
    letters: ['H','A','U','N','T'],
    words: ['HAUNT','AUNT','HUNT','THAN','ANT','HAT','HUT','NAH','NTH','NUT'], bonus: ['HANT'],
    defs: {
      HAUNT: 'To linger restlessly; in Eternal Night, the dead return to haunt the places they once held',
      AUNT: 'A sister of one\'s parent',
      HUNT: 'To pursue prey',
      THAN: 'Used in comparisons',
      ANT: 'A small social insect',
      HAT: 'A head covering',
      HUT: 'A small simple shelter',
      NAH: 'Informal "no"',
      NTH: 'The last of an indefinite series',
      NUT: 'A hard-shelled fruit',
      HANT: 'A ghost (regional)',
    }
  },
  {
    theme: 'BEAST', difficulty: 4.0,
    letters: ['B','E','A','S','T'],
    words: ['ABETS','BASTE','BEAST','BEATS','BETAS','ABET','BAST','BATE','BATS','BEAT','BEST'], bonus: [],
    defs: {
      ABETS: 'Encourages or assists in wrongdoing',
      BASTE: 'To moisten while cooking',
      BEAST: 'A wild creature; in Eternal Night, beasts roam the hex grid and harden the fog of war',
      BEATS: 'Strikes repeatedly',
      BETAS: 'Pre-release software versions; second letters',
      ABET: 'To assist in wrongdoing',
      BAST: 'Fibrous inner bark used for cordage',
      BATE: 'To restrain or lessen',
      BATS: 'Plural of bat',
      BEAT: 'To strike repeatedly; a rhythm',
      BEST: 'Of the highest quality',
    }
  },
  {
    theme: 'BLADE', difficulty: 4.3,
    letters: ['B','L','A','D','E'],
    words: ['ABLED','BALED','BLADE','ABED','ABLE','BALD','BALE','BEAD','BLED','DALE','DEAL','LADE'], bonus: [],
    defs: {
      ABLED: 'Capable',
      BALED: 'Bundled tightly',
      BLADE: 'The edge of a weapon — and in Eternal Night, blades dull with each strike under the durability system',
      ABED: 'In bed',
      ABLE: 'Having power or skill',
      BALD: 'Without hair',
      BALE: 'A bundle of compressed material',
      BEAD: 'A small decorative ball',
      BLED: 'Past tense of bleed',
      DALE: 'A valley',
      DEAL: 'To distribute; an arrangement',
      LADE: 'To load cargo',
    }
  },
  {
    theme: 'SHADE', difficulty: 4.7,
    letters: ['S','H','A','D','E'],
    words: ['ASHED','HEADS','SHADE','AHED','DASH','HAES','HEAD','SHEA','SHED','ADS','ASH','HAD','HAE'], bonus: [],
    defs: {
      ASHED: 'Reduced to ash',
      HEADS: 'Tops of bodies; coin sides',
      SHADE: 'A spirit; a degree of darkness — Eternal Night runs on shades of light and shadow',
      AHED: 'Said "ah"',
      DASH: 'To rush; a short line',
      HAES: 'Plural of hae; Scottish "to have"',
      HEAD: 'The uppermost body part',
      SHEA: 'A tree yielding nuts and oil',
      SHED: 'A small storage building',
      ADS: 'Advertisements',
      ASH: 'Powdery residue of fire',
      HAD: 'Past tense of have',
      HAE: 'To have (Scottish)',
    }
  },
  {
    theme: 'SHADOW', difficulty: 5.5,
    letters: ['S','H','A','D','O','W'],
    words: ['SHADOW','DASH','HAWS','HOWS','SHAD','SHOW','WASH','WOAD','ADS','AHS','ASH','HAD','HAS'], bonus: [],
    defs: {
      SHADOW: 'A region of darkness — Eternal Night players track shadows to find safe ground',
      DASH: 'To rush; a short line',
      HAWS: 'Hesitations in speech',
      HOWS: 'Plural of how',
      SHAD: 'A herring-like fish',
      SHOW: 'To display',
      WASH: 'To clean with water',
      WOAD: 'A blue dye plant',
      ADS: 'Advertisements',
      AHS: 'Exclamations',
      ASH: 'Powdery residue of fire',
      HAD: 'Past tense of have',
      HAS: 'Possesses',
    }
  },
  {
    theme: 'COSMIC', difficulty: 6.2,
    letters: ['C','O','S','M','I','C'],
    words: ['COSMIC','COMIC','MOCS','COMS','MICS','CIS','COS','ICS','MIC','SIC'], bonus: [],
    defs: {
      COSMIC: 'Of the cosmos; the Cosmic Hunt event in Eternal Night offers escalating rewards to bold parties',
      COMIC: 'Funny; a comedian',
      MOCS: 'Plural of moc; moccasins',
      COMS: 'Communications',
      MICS: 'Microphones',
      CIS: 'On the near side',
      COS: 'A variety of lettuce',
      ICS: 'Plural of ic',
      MIC: 'A microphone',
      SIC: 'Thus written (Latin)',
    }
  },
  {
    theme: 'WIZARD', difficulty: 7.0,
    letters: ['W','I','Z','A','R','D'],
    words: ['WIZARD','DRAW','RAID','WARD','ARID','AID','AIR','RAD','WAD','WAR','WIZ','RID','ADZ','DAW','RAW'], bonus: [],
    defs: {
      WIZARD: 'A practitioner of magic; in Eternal Night, wizards channel the Awakened State to cast elemental power',
      DRAW: 'Sketch',
      RAID: 'Sudden attack',
      WARD: 'Protected area',
      ARID: 'Dry',
      AID: 'Help',
      AIR: 'The atmosphere',
      RAD: 'A unit of radiation',
      WAD: 'A small mass',
      WAR: 'Armed conflict',
      WIZ: 'A whiz; a wizard',
      RID: 'To free from something unwanted',
      ADZ: 'A cutting tool',
      DAW: 'A jackdaw',
      RAW: 'Uncooked; in a natural state',
    }
  },
  {
    theme: 'BANISH', difficulty: 7.5,
    letters: ['B','A','N','I','S','H'],
    words: ['BANISH','BAINS','BASIN','BANI','BANS','BASH','BIAS','HABS','NABS','NIBS','SHIN','ABS','AHS','ANI','BAH','BAN'], bonus: ['NAIB'],
    defs: {
      BANISH: 'To drive out by force or rite — banishment seals foes back beyond the veil',
      BAINS: 'Plural of bain; a bath or covering',
      BASIN: 'A wide shallow bowl',
      BANI: 'Plural of ban; a Romanian monetary unit',
      BANS: 'Prohibitions',
      BASH: 'To strike forcefully',
      BIAS: 'A preference or slant',
      HABS: 'Habits (informal)',
      NABS: 'Catches suddenly',
      NIBS: 'Pen tips',
      SHIN: 'The front of the lower leg',
      ABS: 'Abdominal muscles',
      AHS: 'Exclamations',
      ANI: 'A black tropical bird',
      BAH: 'Expression of contempt',
      BAN: 'To prohibit',
      NAIB: 'A deputy ruler',
    }
  },
  {
    theme: 'SCYTHE', difficulty: 8.0,
    letters: ['S','C','Y','T','H','E'],
    words: ['SCYTHE','CHEST','TECH','ETCH','HEST','HYES','THEY','TYES','CYST','SECT','CYTE','ETH','HEY','TYE','YES','YET'], bonus: [],
    defs: {
      SCYTHE: 'A long curved blade; the iconic weapon of reapers and harvesters of the night',
      CHEST: 'The upper torso; a large box',
      TECH: 'Technology',
      ETCH: 'To engrave with acid',
      HEST: 'A command (archaic)',
      HYES: 'Plural of hye',
      THEY: 'Third person plural pronoun',
      TYES: 'Chains or ropes',
      CYST: 'A fluid-filled sac',
      SECT: 'A religious subgroup',
      CYTE: 'A cell (suffix-noun)',
      ETH: 'An old English letter',
      HEY: 'A call for attention',
      TYE: 'A chain or rope',
      YES: 'An affirmative',
      YET: 'Up to now',
    }
  },
  {
    theme: 'LANTERN', difficulty: 8.5,
    letters: ['L','A','N','T','E','R','N'],
    words: ['LANTERN','ANTLER','RENTAL','LANER','LATEN','LATER','LEANT','LEARN','ANTE','EARN','LANE','LEAN','NEAR','RANT','RATE','RENT','TEAR','TERN'], bonus: ['TANNER'],
    defs: {
      LANTERN: 'A portable lamp; in Eternal Night, your lantern is the line between you and the dark',
      ANTLER: 'A deer horn',
      RENTAL: 'Something rented',
      LANER: 'A driver who keeps to one lane',
      LATEN: 'To become late',
      LATER: 'Afterwards',
      LEANT: 'Past tense of lean (British)',
      LEARN: 'To acquire knowledge',
      ANTE: 'A poker stake',
      EARN: 'To gain by work',
      LANE: 'A narrow road',
      LEAN: 'To incline',
      NEAR: 'Close in distance',
      RANT: 'A loud tirade',
      RATE: 'A measured quantity',
      RENT: 'Payment for use',
      TEAR: 'A drop from the eye; to rip',
      TERN: 'A seabird',
      TANNER: 'One who tans leather; a sixpence',
    }
  },
  {
    theme: 'PHANTOM', difficulty: 9.0,
    letters: ['P','H','A','N','T','O','M'],
    words: ['PHANTOM','PATHO','ATOM','HOMA','MATH','MOAN','MOAT','MOTH','OATH','PATH','PHAT','TAMP','AMP','APT','HAM','HOP','HOT','MAP'], bonus: ['HOPMAN'],
    defs: {
      PHANTOM: 'A ghost; phantoms phase through fog of war and strike before being seen',
      PATHO: 'Suffering (prefix)',
      ATOM: 'The basic unit of matter',
      HOMA: 'A sacrificial fire',
      MATH: 'The study of numbers',
      MOAN: 'A low sound of pain',
      MOAT: 'A defensive ditch',
      MOTH: 'A flying insect related to butterflies',
      OATH: 'A solemn vow',
      PATH: 'A trodden way',
      PHAT: 'Excellent (slang)',
      TAMP: 'To pack down tightly',
      AMP: 'An ampere',
      APT: 'Suitable',
      HAM: 'Cured pig meat',
      HOP: 'To jump on one leg',
      HOT: 'Of high temperature',
      MAP: 'A drawn representation of land',
      HOPMAN: 'A picker of hops',
    }
  },
  {
    theme: 'VAMPIRE', difficulty: 9.5,
    letters: ['V','A','M','P','I','R','E'],
    words: ['VAMPIRE','VAMPER','PRIMA','PRIME','VIPER','PAIR','PARE','PAVE','PRIM','RAMP','RAVE','REAM','REAP','RIPE','VAMP','AIM','AIR','AMP','APE'], bonus: [],
    defs: {
      VAMPIRE: 'An undead blood-drinker; vampires rule the deepest hours of the eternal night',
      VAMPER: 'One who vamps; an improviser',
      PRIMA: 'First; principal (Italian — as in prima donna)',
      PRIME: 'Of first quality',
      VIPER: 'A venomous snake',
      PAIR: 'Two of a kind',
      PARE: 'To trim',
      PAVE: 'To cover with a hard surface',
      PRIM: 'Properly correct',
      RAMP: 'A sloping surface',
      RAVE: 'To talk wildly; a dance event',
      REAM: 'A quantity of paper',
      REAP: 'To harvest',
      RIPE: 'Fully developed',
      VAMP: 'A seductive woman; to improvise',
      AIM: 'To direct',
      AIR: 'The atmosphere',
      AMP: 'An ampere',
      APE: 'A primate',
    }
  },
  {
    theme: 'REVENANT', difficulty: 10.0,
    letters: ['R','E','V','E','N','A','N','T'],
    words: ['REVENANT','NEATER','TANNER','EATEN','EVENT','NERVE','NEVER','RAVEN','ANTE','EARN','NEAR','RANT','RATE','RENT','TERN','ANE','ARE','ART','ATE','AVE'], bonus: ['TERNE'],
    defs: {
      REVENANT: 'A corpse returned from death; revenants carry the grudges that killed them',
      NEATER: 'More orderly',
      TANNER: 'One who tans leather; a sixpence',
      EATEN: 'Consumed',
      EVENT: 'A happening',
      NERVE: 'A bodily fiber; boldness',
      NEVER: 'Not ever',
      RAVEN: 'A large black bird',
      ANTE: 'A poker stake',
      EARN: 'To gain by work',
      NEAR: 'Close in distance',
      RANT: 'A loud tirade',
      RATE: 'A measured quantity',
      RENT: 'Payment for use',
      TERN: 'A seabird',
      ANE: 'One',
      ARE: 'Form of be',
      ART: 'Creative expression',
      ATE: 'Past tense of eat',
      AVE: 'A greeting (Latin)',
      TERNE: 'A tin-lead alloy',
    }
  },
  {
    theme: 'TWILIGHT', difficulty: 10.5,
    letters: ['T','W','I','L','I','G','H','T'],
    words: ['TWILIGHT','LIGHT','TILT','WILT','GILT','WHIT','WHIG','WIGHT','HILT','WIT','LIT','HIT','GIT','WIG'], bonus: [],
    defs: {
      TWILIGHT: 'The dim border between day and night — and the safest hour to travel in Eternal Night',
      LIGHT: 'Illumination; bright',
      TILT: 'A slant',
      WILT: 'To droop',
      GILT: 'Covered with gold',
      WHIT: 'A small amount',
      WHIG: 'A historical political party',
      WIGHT: 'A spirit or being (archaic)',
      HILT: 'The handle of a sword',
      WIT: 'Clever humor',
      LIT: 'Past tense of light; illuminated',
      HIT: 'A successful strike',
      GIT: 'A scoundrel (Brit.)',
      WIG: 'A head covering of hair',
    }
  },
  {
    theme: 'AWAKENED', difficulty: 11.0,
    letters: ['A','W','A','K','E','N','E','D'],
    words: ['AWAKENED','AWAKED','AWAKEN','WEAKEN','AWAKE','WAKED','WAKEN','ANEW','AWED','DANK','DAWN','DEAN','KEEN','KNEW','NEED','WAKE','WANE','WEAK','WEAN','WEEK'], bonus: ['WEANED'],
    defs: {
      AWAKENED: 'Roused; in Eternal Night, the empowered combat mode',
      AWAKED: 'Past tense of awake',
      AWAKEN: 'To rouse from sleep',
      WEAKEN: 'To make weak',
      AWAKE: 'Conscious',
      WAKED: 'Past tense of wake',
      WAKEN: 'To rouse',
      ANEW: 'Once more',
      AWED: 'Filled with awe',
      DANK: 'Damp and cold',
      DAWN: 'Daybreak',
      DEAN: 'A senior official',
      KEEN: 'Sharp; mourning chant',
      KNEW: 'Past tense of know',
      NEED: 'A requirement',
      WAKE: 'To rouse from sleep',
      WANE: 'To diminish',
      WEAK: 'Lacking strength',
      WEAN: 'To gradually withdraw',
      WEEK: 'A period of 7 days',
      WEANED: 'Gradually withdrawn from a need',
    }
  },
  {
    theme: 'SANCTUARY', difficulty: 11.5,
    letters: ['S','A','N','C','T','U','A','R','Y'],
    words: ['SANCTUARY','CRUSTY','NASTY','RUSTY','SATAN','SAUNA','SCANT','ANTS','ARTS','CANT','CARS','CART','CURT','SCAT','STAR','STUN','TANS','ANT','CAN','CAR'], bonus: [],
    defs: {
      SANCTUARY: 'A holy refuge; sanctuaries in Eternal Night are warded sites the dark cannot enter',
      CRUSTY: 'Hard-crusted; surly',
      NASTY: 'Unpleasant',
      RUSTY: 'Coated with rust',
      SATAN: 'The adversary in many religions',
      SAUNA: 'A heated room for bathing',
      SCANT: 'Barely enough',
      ANTS: 'Plural of ant',
      ARTS: 'Creative works',
      CANT: 'A tilt; jargon',
      CARS: 'Plural of car',
      CART: 'A two-wheeled vehicle',
      CURT: 'Brusquely brief',
      SCAT: 'To go away; jazz vocals',
      STAR: 'A celestial body',
      STUN: 'To daze',
      TANS: 'Browns from sun',
      ANT: 'A small social insect',
      CAN: 'A metal container',
      CAR: 'A motor vehicle',
    }
  },
  {
    theme: 'NIGHTFALL', difficulty: 12.0,
    letters: ['N','I','G','H','T','F','A','L','L'],
    words: ['NIGHTFALL','FLIGHT','FIGHT','FILTH','FLAIL','LIGHT','FAIL','FALL','FILL','FLAG','FLAT','GAIN','GAIT','HALF','HALT','NAIL','TAIL','TALL','FAN','FAT'], bonus: [],
    defs: {
      NIGHTFALL: 'The onset of darkness — when the Eternal Night begins each cycle and danger spikes',
      FLIGHT: 'The act of flying',
      FIGHT: 'A conflict',
      FILTH: 'Dirt',
      FLAIL: 'To wave wildly',
      LIGHT: 'Illumination; bright',
      FAIL: 'To fall short',
      FALL: 'To drop down',
      FILL: 'To make full',
      FLAG: 'A banner',
      FLAT: 'Level; an apartment',
      GAIN: 'To acquire',
      GAIT: 'A manner of walking',
      HALF: 'One of two parts',
      HALT: 'To stop',
      NAIL: 'A fastener; a fingernail',
      TAIL: 'A rear appendage',
      TALL: 'Of great height',
      FAN: 'A device for moving air',
      FAT: 'Greasy tissue',
    }
  },
  {
    theme: 'BLOODMOON', difficulty: 12.5,
    letters: ['B','L','O','O','D','M','O','O','N'],
    words: ['BLOODMOON','BLOOM','BLOOD','BLOND','BOOM','DOOM','LOOM','LOON','MOOD','MOON','BOND','BOON','BOLD','MOD','NOB','NOD','BOO','MOO','OOM'], bonus: ['MOOLI'],
    defs: {
      BLOODMOON: 'A red-shadowed moon; bloodmoons in Eternal Night summon World Bosses across the realm',
      BLOOM: 'A flower',
      BLOOD: 'The red bodily fluid',
      BLOND: 'Light-colored',
      BOOM: 'A loud noise',
      DOOM: 'A grim fate',
      LOOM: 'A weaving machine; to appear large',
      LOON: 'A diving bird; a fool',
      MOOD: 'A state of mind',
      MOON: 'Earth\'s satellite',
      BOND: 'A binding agreement',
      BOON: 'A blessing',
      BOLD: 'Brave',
      MOD: 'A modification',
      NOB: 'A wealthy or important person',
      NOD: 'To bow the head briefly',
      BOO: 'A shout of disapproval',
      MOO: 'The sound of a cow',
      OOM: 'Older relative (informal)',
      MOOLI: 'A white radish; bonus word',
    }
  },
  {
    theme: 'UNDERWORLD', difficulty: 13.0,
    letters: ['U','N','D','E','R','W','O','R','L','D'],
    words: ['UNDERWORLD','REWOUND','DOWNER','REWORD','WONDER','DRONE','DROWN','LOWER','OWNED','ROUND','UNDER','WORLD','WOUND','DOUR','DOWN','DURE','LEND','LEWD','LOUR','LOWE'], bonus: [],
    defs: {
      UNDERWORLD: 'The realm of the dead beneath Mirandus — entered only by the bravest and the lost',
      REWOUND: 'Rewound (as a clock)',
      DOWNER: 'A depressing experience',
      REWORD: 'To rephrase',
      WONDER: 'Awe',
      DRONE: 'A continuous low hum',
      DROWN: 'To suffocate in liquid',
      LOWER: 'Less high; to drop',
      OWNED: 'Possessed',
      ROUND: 'Spherical',
      UNDER: 'Below',
      WORLD: 'Earth',
      WOUND: 'An injury; coiled',
      DOUR: 'Stern and gloomy',
      DOWN: 'Toward a lower place',
      DURE: 'To endure (archaic)',
      LEND: 'To give temporarily',
      LEWD: 'Crude or lustful',
      LOUR: 'To look threatening; to scowl',
      LOWE: 'A flame (Scottish dialect)',
    }
  },
]
