import type { Level } from '../types.js'

export const MIRANDUS_LEVELS: Level[] = [
  {
    theme: 'HAMLET', difficulty: 5.5,
    letters: ['H','A','M','L','E','T'],
    words: ['HAMLET','HALT','HATE','HEAT','LAME','LATE','MALE','MALT','MATE','MATH'], bonus: ['METAL'],
    defs: {
      ALE:    'A type of beer',
      ALT:    'Alternative; the Alt key; short for alt-coin',
      ATE:    'Past tense of eat',
      EAT:    'To consume food',
      ELM:    'A tall deciduous tree',
      HAM:    'Cured pig meat; an over-actor',
      HEM:    'The folded edge of a garment; to surround',
      LAM:    'To beat; on the lam means fleeing',
      LAT:    'A muscle; latitude',
      MAT:    'A flat floor covering',
      MET:    'Past tense of meet',
      HALT:   'A stop; to cease moving',
      HATE:   'Intense dislike',
      HEAT:   'Thermal energy',
      LAME:   'Unable to walk properly; weak or unconvincing',
      LATE:   'After the expected time',
      MALE:   'Of the masculine sex',
      MALT:   'Germinated grain used in brewing',
      MATH:   'The study of numbers',
      MATE:   'A companion; to pair for reproduction',
      MEAL:   'Food eaten at a sitting',
      MEAT:   'Animal flesh as food',
      TALE:   'A story or narrative',
      TAME:   'Not wild; to domesticate',
      TEAM:   'A group working together',
      TEAL:   'A blue-green color',
      HAMLET: 'In Mirandus, Hamlets are mid-tier land deeds — player-owned settlements that can host buildings, attract residents, and form the backbone of the player-driven economy',
      METAL:  'A solid mineral material; relating to heavy music',
    }
  },
  {
    theme: 'CITADEL', difficulty: 7.8,
    letters: ['C','I','T','A','D','E','L'],
    words: ['CITADEL','CITED','IDEAL','TIDAL','TILED','ACED','DACE','DATE','DEAL','DIAL'], bonus: ['EDICT'],
    defs: {
      ACE:     'An expert; a playing card',
      AID:     'Help or assistance',
      ATE:     'Past tense of eat',
      EAT:     'To consume food',
      ICE:     'Frozen water',
      LAD:     'A boy or young man',
      LET:     'To allow; to rent',
      LIT:     'Past tense of light; illuminated',
      TIE:     'A bond; a necktie; to fasten',
      ACED:    'Past tense of ace — to score perfectly',
      DACE:    'A small freshwater fish',
      DATE:    'A specific day; a social meeting; a fruit',
      DEAL:    'A transaction; to distribute cards',
      DIAL:    'A circular face; to call a number',
      DIET:    'Food and drink habits; a restricted eating plan',
      EDIT:    'To revise or correct',
      IDEA:    'A thought or concept',
      LACE:    'A delicate fabric; to thread',
      CITED:   'Referred to as an example; summoned officially',
      TILED:   'Covered with tiles',
      TIDAL:   'Relating to ocean tides',
      IDEAL:   'Perfect; a standard of perfection',
      CITADEL: 'In Mirandus, Citadels are the rarest and largest land deeds — the Five Great Citadels are ruled by player-kings and serve as the political and economic centers of the entire realm',
      EDICT:   'An official order or proclamation',
    }
  },
  {
    theme: 'CARAVEL', difficulty: 7.5,
    letters: ['C','A','R','A','V','E','L'],
    words: ['CARAVEL','CARVE','CRAVE','RAVEL','ACRE','LACE','LAVE','RACE','RAVE','VALE','VEAL'], bonus: ['ACER'],
    defs: {
      ACE:     'An expert; a playing card',
      ALE:     'A type of beer',
      ARC:     'A curved line',
      ARE:     'Second person singular of "be"',
      AVE:     'An avenue; a greeting (Latin)',
      CAR:     'A motor vehicle',
      EAR:     'The organ of hearing',
      ERA:     'A long period of time',
      LAC:     'A resinous substance secreted by insects',
      ACRE:    'A unit of land area',
      LAVE:    'To wash; to flow along',
      LACE:    'A delicate fabric; to thread',
      RACE:    'A competition; an ethnic group',
      RAVE:    'To talk wildly; an all-night party',
      VEAL:    'Meat from a young calf',
      VALE:    'A valley; farewell (archaic)',
      RAVEL:   'To untangle; to entangle (paradoxically both meanings)',
      CARVE:   'To cut into a solid material',
      CRAVE:   'To feel a powerful desire for',
      CARAVEL: 'In Mirandus, the Caravel is the largest ship NFT — a swift sea vessel capable of carrying large crews and cargo, perfect for long trade voyages between player ports',
      ACER:    'A genus of maple trees',
    }
  },
  {
    theme: 'MATERIUM', difficulty: 9.2,
    letters: ['M','A','T','E','R','I','U','M'],
    words: ['MATERIUM','MARE','MATE','MIRE','MITE','RATE','REAM','RIME','RITE','TEAM','TIER','TIRE'], bonus: ['IMAM'],
    defs: {
      AIM:      'To point at a target; an objective',
      AIT:      'A small island, especially in a river',
      ART:      'Creative expression',
      EAR:      'The organ of hearing',
      EMU:      'A large flightless Australian bird',
      ERA:      'A long period of time',
      IRE:      'Anger or wrath',
      MAT:      'A flat floor covering',
      MARE:     'A female horse',
      MATE:     'A companion; to pair for reproduction',
      MIRE:     'Swampy ground; to be stuck',
      MITE:     'A tiny arachnid; a small contribution',
      RATE:     'A measure or speed; to evaluate',
      REAM:     'A quantity of paper; to widen a hole',
      RIME:     'Frost; archaic word for rhyme',
      RITE:     'A religious or solemn ceremony',
      TEAM:     'A group working together',
      TIER:     'A level or rank',
      TIRE:     'To grow weary; a rubber wheel covering',
      TRIM:     'To cut neatly; neat and tidy',
      TRUE:     'Accurate; genuine',
      MATERIUM: 'The magical resource at the heart of Mirandus — Materium is a rare substance mined by players that powers enchantments, crafting, and advanced game mechanics. It is the primary economic resource of the realm',
      IMAM:     'A Muslim religious leader',
    }
  },
  {
    theme: 'MIRANDUS', difficulty: 11.0,
    letters: ['M','I','R','A','N','D','U','S'],
    words: ['MIRANDUS','DRAIN','AMID','DAIS','DRAM','MAID','MAIN','RANI','RIND','RUIN','SAND','AID','AIM'], bonus: [],
    defs: {
      AID:      'Help or assistance',
      AIM:      'To point at a target; an objective',
      AIR:      'The gaseous atmosphere; to broadcast',
      AND:      'Used to join words or clauses',
      ANI:      'A tropical American bird',
      DIM:      'Not bright; to reduce light',
      DIN:      'A loud noise',
      MAD:      'Angry; insane',
      MAN:      'An adult male human',
      MUD:      'Wet earth',
      RAN:      'Past tense of run',
      RIM:      'The outer edge',
      RUN:      'To move quickly on foot',
      DAIS:     'A raised platform for a speaker or throne',
      DRAM:     'A small amount of whiskey; a unit of weight',
      MAID:     'A female servant; an unmarried woman (archaic)',
      MAIN:     'Chief; principal; a water pipe',
      RANI:     'A Hindu queen',
      RIND:     'The tough outer layer of fruit',
      RUIN:     'Destruction; to destroy',
      SAND:     'Fine granular material; to smooth with sandpaper',
      AMID:     'Surrounded by; in the middle of',
      DRAIN:    'To remove liquid; a pipe for wastewater',
      MIRANDUS: 'A fantasy blockchain MMORPG by Gala Games — players explore, battle, craft, and trade in an open world where everything from land to buildings to ships are player-owned NFTs',
    }
  },
  {
    theme: 'EXEMPLAR', difficulty: 10.5,
    letters: ['E','X','E','M','P','L','A','R'],
    words: ['EXEMPLAR','EXAMPLE','REPEAL','AMPLE','MAPLE','LAME','LAMP','ALE','APE','ARE','ARM','EAR','EEL'], bonus: ['PEARL'],
    defs: {
      ALE:      'A type of beer',
      APE:      'A large primate; to imitate',
      ARE:      'Second person singular of "be"',
      ARM:      'A limb; to equip',
      EAR:      'The organ of hearing',
      EEL:      'A snake-like fish',
      ELM:      'A tall deciduous tree',
      ERA:      'A long period of time',
      LAP:      'The flat area of thighs when sitting; a circuit',
      LAX:      'Not strict; a type of lacrosse',
      PAL:      'A friend or companion',
      PAR:      'Equal level; standard score in golf',
      PEA:      'A small round green vegetable',
      LAME:     'Unable to walk properly; unconvincing',
      LAMP:     'A device for producing light',
      AMPLE:    'More than enough; plentiful',
      MAPLE:    'A tree known for its sap and distinctive leaves',
      REPEAL:   'To revoke or cancel a law',
      EXAMPLE:  'A representative instance used to illustrate a point',
      EXEMPLAR: 'In Mirandus, Exemplars are legendary avatar NFTs — rare heroes of each race (Human, Elf, Dwarf, Halfling, Orc) with unique abilities and lore that make them the most powerful characters in the game',
      PEARL:    'A gem formed inside an oyster; something precious',
    }
  },
  {
    theme: 'ALCHEMY', difficulty: 7.2,
    letters: ['A','L','C','H','E','M','Y'],
    words: ['ALCHEMY','ACME','CAME','CLAY','EACH','LAME','ACE','ALE','CAM','ELM','HAM','HAY','HEM','LAM'], bonus: ['CLAM'],
    defs: {
      ACE:     'An expert; a playing card',
      ALE:     'A type of beer',
      CAM:     'A rotating piece in a mechanism',
      ELM:     'A tall deciduous tree',
      HAM:     'Cured pig meat',
      HAY:     'Dried grass used as animal feed',
      HEM:     'The folded edge of fabric',
      LAM:     'To beat; on the lam means fleeing',
      LAY:     'To place or put down; past tense of lie',
      ACME:    'The highest point of achievement',
      CAME:    'Past tense of come',
      CLAY:    'A fine-grained natural rock or soil',
      EACH:    'Every one of a group',
      LAME:    'Unable to walk properly; unconvincing',
      ALCHEMY: 'In Mirandus, Alchemy is practiced by Human Exemplar The Alchemist — a master of potion brewing who transforms raw materials into powerful elixirs that affect players in the game world',
      CLAM:    'A bivalve mollusc; to gather clams',
    }
  },
  {
    theme: 'VILLAGE', difficulty: 6.8,
    letters: ['V','I','L','L','A','G','E'],
    words: ['VILLAGE','AGILE','ALIVE','EAGLE','GAVEL','LEGAL','VILLA','EVIL','GALE','GIVE','LAVA','LIVE','VALE','VEIL','VILE'], bonus: ['VILLA'],
    defs: {
      AGE:     'A period of time; to grow older',
      ALE:     'A type of beer',
      EEL:     'A snake-like fish',
      GAL:     'Informal for girl',
      GEL:     'A thick jelly-like substance',
      ILL:     'Sick or unwell',
      LAG:     'To fall behind; a delay',
      LAV:     'Informal for lavatory (British)',
      LIE:     'An untruth; to recline',
      AGILE:   'Able to move quickly and easily',
      ALIVE:   'Living; active',
      EAGLE:   'A large bird of prey',
      GAVEL:   'A small mallet used by judges or auctioneers',
      LEGAL:   'Permitted by law',
      VILLA:   'A large country house',
      VILE:    'Extremely unpleasant',
      VEIL:    'A piece of fine material worn as a covering',
      VALE:    'A valley',
      LIVE:    'To be alive; having life',
      EVIL:    'Profoundly wicked',
      GIVE:    'To freely transfer possession of',
      GALE:    'A strong wind',
      LAVA:    'Molten rock erupted from a volcano',
      VILLAGE: 'In Mirandus, Villages are a tier of land deed between Hamlet and Town — medium-sized settlements where players can build crafting structures and attract adventurers seeking services',
    }
  },
  {
    theme: 'BREWERY', difficulty: 7.0,
    letters: ['B','R','E','W','E','R','Y'],
    words: ['BEY','BEW','BRR','BYE','EWE','REW','RYE','WEB','WEE','YEW','BEER','BREW','EYRE','WERE','EVERY','BREWERY'], bonus: ['WEBER'],
    defs: {
      BEY:     'A Turkish title of respect',
      BYE:     'Farewell; advancing without playing in a tournament',
      EWE:     'A female sheep',
      RYE:     'A cereal grain',
      WEB:     'A spider\'s silk structure; the internet',
      WEE:     'Very small; to urinate (informal)',
      YEW:     'An evergreen tree',
      BEER:    'An alcoholic drink brewed from malted grain',
      BREW:    'To make beer or tea; a storm brewing',
      EYRE:    'A journey circuit made by judges in England (historical)',
      WERE:    'Past tense of be',
      EVERY:   'Each one of a group without exception',
      BREWERY: 'In Mirandus, the Large Brewery and Small Brewery are building NFTs that produce ale and other beverages — essential for healing adventurers and an important trade good in settlements',
      WEBER:   'A unit of magnetic flux; also a surname',
    }
  },
  {
    theme: 'TAVERN', difficulty: 6.2,
    letters: ['T','A','V','E','R','N'],
    words: ['TAVERN','VERNAL','NERVE','RAVEN','EARN','NAVE','RANT','RANT','RATE','RENT','VANE','ANT','ART','AVE','EAR','ERA','NET'], bonus: ['RAVEN'],
    defs: {
      ANT:    'A small insect that lives in colonies',
      ART:    'Creative expression',
      AVE:    'An avenue; a greeting (Latin)',
      EAR:    'The organ of hearing',
      ERA:    'A long period of time',
      NET:    'A mesh; remaining after deductions',
      RAN:    'Past tense of run',
      RAT:    'A rodent; an informer',
      TAN:    'A light brown color',
      TAR:    'A dark sticky substance',
      TEN:    'The number 10',
      EARN:   'To receive payment',
      NAVE:   'The central part of a church',
      RANT:   'To speak angrily',
      RATE:   'A measure or speed',
      RENT:   'Payment for use',
      VANE:   'A blade that rotates in wind or water',
      NERVE:  'A fiber transmitting signals; courage',
      TAVERN: 'In Mirandus, Taverns are resting structures where adventurers recover health and stamina — player-owned taverns charge fees and are a core part of the service economy in settlements',
      RAVEN:  'A large black bird; jet-black in color',
    }
  },
  {
    theme: 'ARMORER', difficulty: 7.5,
    letters: ['A','R','M','O','R','E','R'],
    words: ['ARE','ARM','EAR','ERA','MAR','OAR','ORE','MARE','ROAR','RARE','ROAM','REAM','ARMOR','ARMORER'], bonus: ['MERER'],
    defs: {
      ARE:     'Second person singular of "be"',
      ARM:     'A limb; to equip with weapons',
      EAR:     'The organ of hearing',
      ERA:     'A long period of time',
      MAR:     'To damage or spoil',
      OAR:     'A rowing pole',
      ORE:     'Rock containing valuable minerals',
      MARE:    'A female horse',
      ROAR:    'A deep loud sound',
      RARE:    'Uncommon; undercooked meat',
      ROAM:    'To travel without fixed destination',
      REAM:    'A quantity of paper; to widen a hole',
      ARMOR:   'Protective covering worn in battle',
      ARMORER: 'In Mirandus, the Armorer is a crafting building where players commission and upgrade armor — essential for adventurers venturing into dangerous regions of the realm',
    }
  },
  {
    theme: 'DUNGEON', difficulty: 7.0,
    letters: ['D','U','N','G','E','O','N'],
    words: ['DUNGEON','DONGE','DONE','DONG','DUNE','DUNG','GONE','GONE','HONE','NODE','NOUN','NUDE','UNDO','DEN','DOE','DON','DUE','DUG'], bonus: ['GOUGE'],
    defs: {
      DEN:     'A cozy room; an animal\'s lair',
      DOE:     'A female deer',
      DON:     'To put on clothing; a university lecturer',
      DUE:     'Owed; expected',
      DUG:     'Past tense of dig',
      DUN:     'A dull greyish-brown color',
      EON:     'An indefinitely long period',
      GUN:     'A firearm',
      NOD:     'A downward head movement of agreement',
      ODE:     'A type of lyric poem',
      DONE:    'Completed',
      DUNE:    'A sand hill formed by wind',
      GONE:    'Departed; no longer present',
      NODE:    'A point in a network',
      NUDE:    'Naked; a work of art depicting a naked person',
      UNDO:    'To reverse an action',
      DUNG:    'Animal excrement used as fertilizer',
      NOUN:    'A word naming a person, place, or thing',
      DUNGEON: 'In Mirandus, Dungeons are dangerous locations scattered across the realm — adventurers enter to battle monsters, discover rare loot, and mine for Materium',
    }
  },
  {
    theme: 'ENCHANT', difficulty: 7.8,
    letters: ['E','N','C','H','A','N','T'],
    words: ['ENCHANT','TENANT','NATCH','TEACH','ANTE','CANT','EACH','ETCH','HATE','HEAT','ACE','ANT','ATE','CAN','EAT','HAT','HEN','NET','TAN'], bonus: ['CHANCE'],
    defs: {
      ACE:     'An expert; a playing card',
      ANT:     'A small colony insect',
      ATE:     'Past tense of eat',
      CAN:     'To be able to; a metal container',
      EAT:     'To consume food',
      HAT:     'A head covering',
      HEN:     'A female chicken',
      NET:     'A mesh; remaining after deductions',
      TAN:     'A light brown color',
      TEN:     'The number 10',
      THE:     'Definite article',
      ANTE:    'A stake put in before the deal in poker',
      CANT:    'Insincere talk; to tilt',
      EACH:    'Every one of a group',
      ETCH:    'To engrave using acid or tools',
      HATE:    'Intense dislike',
      HEAT:    'Thermal energy',
      TEACH:   'To instruct or educate',
      ENCHANT: 'In Mirandus, enchanting is a powerful crafting system — players use Materium to add magical properties to weapons, armor, and items, making them significantly more effective in battle',
    }
  },
  {
    theme: 'TEMPLE', difficulty: 6.0,
    letters: ['T','E','M','P','L','E'],
    words: ['EEL','ELM','EMU','LET','MET','PET','MELT','MEET','PEEL','PELT','FELT','TEMPLE'], bonus: ['METTLE'],
    defs: {
      EEL:    'A snake-like fish',
      ELM:    'A tall deciduous tree',
      EMU:    'A large flightless bird',
      LET:    'To allow; to rent',
      MET:    'Past tense of meet',
      PET:    'A domesticated animal; to stroke',
      MELT:   'To become liquid from heat',
      MEET:   'To encounter; appropriate',
      PEEL:   'To remove skin; the skin of a fruit',
      PELT:   'An animal skin; to throw things at',
      FELT:   'Past tense of feel; a type of fabric',
      TEMPLE: 'In Mirandus, Temples are sacred structures that players can build on their land deeds — they provide spiritual bonuses, host resurrection services, and are centers of the divine power that permeates the realm',
    }
  },
  {
    theme: 'WARLORD', difficulty: 8.5,
    letters: ['W','A','R','L','O','R','D'],
    words: ['WARLORD','DRAW','LOAD','LORD','ROAD','ROAR','WARD','WOAD','WORD','DOL','LAD','LAR','LAW','LOW','OAF','OAR','OWL','RAW','ROD','ROW'], bonus: ['DOLOR'],
    defs: {
      LAD:     'A boy or young man',
      LAW:     'A rule enforced by authority',
      LORD:    'A man of high rank; a ruler',
      OAR:     'A rowing pole',
      OWL:     'A nocturnal bird of prey',
      RAW:     'Uncooked; unprocessed',
      ROD:     'A thin straight bar; a fishing rod',
      ROW:     'A line; to propel a boat; a quarrel',
      WAD:     'A mass of soft material; a bundle of money',
      WAR:     'Armed conflict between states or groups',
      DRAW:    'To sketch; a tied result',
      LOAD:    'A weight being carried; to place cargo',
      ROAD:    'A path for vehicles',
      ROAR:    'A deep loud sound',
      WARD:    'A division of a hospital; to guard against',
      WORD:    'A unit of language',
      WOAD:    'A blue dye plant used by ancient Britons',
      WARLORD: 'In Mirandus, Warlords are powerful player-controlled characters who command armies and control territory — they levy taxes, engage in conquest, and defend their holdings against rival factions',
    }
  },
  {
    theme: 'POTION', difficulty: 5.8,
    letters: ['P','O','T','I','O','N'],
    words: ['POTION','OPTIC','POINT','PONIT','INTO','LION','NOON','NOOP','ONTO','PINT','PION','ION','NIP','NIT','NOT','OPT','PIN','PIT','POI','POT'], bonus: ['OPTION'],
    defs: {
      ION:    'An electrically charged atom',
      NIP:    'A small drink; to bite sharply; cold weather',
      NIT:    'A louse egg; to pick faults',
      NOT:    'Negation',
      OPT:    'To choose',
      PIN:    'A small fastener; to fasten',
      PIT:    'A hole in the ground',
      POI:    'A Hawaiian food from taro',
      POT:    'A container; the total prize pool',
      TIN:    'A metal; a sealed container',
      TIP:    'The pointed end; a gratuity; advice',
      TON:    'A unit of weight',
      TOP:    'The highest point',
      INTO:   'Moving inward',
      LION:   'A large African cat',
      PINT:   'A unit of liquid measure',
      ONTO:   'Moving to a position on',
      POINT:  'A location; a unit of scoring; to indicate',
      POTION: 'In Mirandus, Potions are crafted at Potion structures like the Small and Large Apothecary — players use them to heal, boost stats, or gain temporary abilities during adventures',
      OPTION: 'A choice; a right to buy or sell at an agreed price',
    }
  },
  {
    theme: 'FORGE', difficulty: 4.8,
    letters: ['F','O','R','G','E'],
    words: ['ERG','FOR','FOG','FRO','GOE','GOT','ORE','ROE','ROG','FORE','FROG','GORE','OGRE','FORGE'], bonus: ['ERGO'],
    defs: {
      ERG:   'A unit of energy',
      FOR:   'In favor of; intended to belong to',
      FOG:   'Thick mist',
      FRO:   'From (archaic); to and fro means back and forth',
      ORE:   'Rock containing valuable minerals',
      ROE:   'Fish eggs',
      FORE:  'At the front; a warning shout in golf',
      FROG:  'An amphibian; a fastening on a coat',
      GORE:  'Blood; to pierce with horns',
      OGRE:  'A fierce giant in folklore',
      FORGE: 'In Mirandus, the Forge is a weapon crafting structure where players commission swords, axes, and other weapons — quality depends on materials and the blacksmith\'s skill level',
      ERGO:  'Therefore (Latin)',
    }
  },
  {
    theme: 'KINGDOM', difficulty: 8.0,
    letters: ['K','I','N','G','D','O','M'],
    words: ['KINGDOM','DINGO','DOING','GNOME','GOON','MIND','MING','MINK','MONK','DIM','DIN','DON','GOD','ION','KID','KIN','MID','MOD','NOD','ODD'], bonus: ['MOOING'],
    defs: {
      DIM:     'Not bright; to reduce light',
      DIN:     'A loud noise',
      DON:     'To put on clothing',
      GOD:     'A divine being',
      ION:     'An electrically charged atom',
      KID:     'A child; a young goat; to tease',
      KIN:     'One\'s family or relatives',
      MID:     'In the middle of',
      MOD:     'Modification; modern style',
      NOD:     'A downward head movement of agreement',
      MIND:    'The intellect; to object to something',
      MONK:    'A member of a religious community',
      MINK:    'A small semi-aquatic mammal; its fur',
      GOON:    'A thug hired to intimidate',
      KINGDOM: 'In Mirandus, the realm is divided into five Kingdoms, each ruled by the owner of a Citadel land deed — kingdoms can form alliances, wage war, and govern the political landscape of the entire game world',
    }
  },
  {
    theme: 'MERCHANT', difficulty: 9.5,
    letters: ['M','E','R','C','H','A','N','T'],
    words: ['MERCHANT','TRANCE','MARCH','RANCH','REACH','TEACH','ARCH','CANE','CANT','CARE','CART','EACH','EARN','ETCH','HARM','HATE','HEAR','HEAT','MENT','RACE'], bonus: ['ENTRAP'],
    defs: {
      ACE:      'An expert; a playing card',
      ANT:      'A small colony insect',
      ARC:      'A curved line',
      ART:      'Creative expression',
      CAN:      'To be able to; a metal container',
      CAR:      'A motor vehicle',
      EAR:      'The organ of hearing',
      ERA:      'A long period of time',
      HAT:      'A head covering',
      HER:      'Belonging to a female person',
      MAN:      'An adult male human',
      MAR:      'To damage or spoil',
      NET:      'A mesh; remaining after deductions',
      TAN:      'A light brown color',
      TAR:      'A dark sticky substance',
      TEN:      'The number 10',
      ARCH:     'A curved structure; mischievous',
      CANE:     'A walking stick; a plant stem',
      CARE:     'Serious attention; to feel concern',
      CART:     'A wheeled vehicle for carrying goods',
      EACH:     'Every one of a group',
      EARN:     'To receive payment for work',
      HARM:     'Physical or mental damage',
      HATE:     'Intense dislike',
      HEAR:     'To perceive sound',
      HEAT:     'Thermal energy',
      RACE:     'A competition; an ethnic group',
      RANT:     'To speak angrily',
      RATE:     'A measure or speed',
      REAM:     'A quantity of paper',
      RENT:     'Payment for use',
      TEAM:     'A group working together',
      MARCH:    'To walk in a military manner; the third month',
      RANCH:    'A large farm for livestock',
      REACH:    'To extend to; distance covered',
      TEACH:    'To instruct or educate',
      MERCHANT: 'In Mirandus, Merchants are player characters who buy low and sell high, moving goods between settlements — they are essential to the player-driven economy and can amass great wealth through trade routes',
    }
  },
  {
    theme: 'RESURRECTION', difficulty: 13.0,
    letters: ['R','E','S','U','R','R','E','C','T','I','O','N'],
    words: ['RESURRECTION','RESURRECT','ERECTION','SECTION','ENTIRE','NOTICE','CURSE','INNER','NURSE','OUTER','SNORE','SONIC','TONIC','CORE','CORN','CURE','CUTE','ERST','INTO','IRON'], bonus: ['SNOUT','NEUTRON'],
    defs: {
      ION:          'An electrically charged atom',
      IRE:          'Anger or wrath',
      NET:          'A mesh; remaining after deductions',
      ORE:          'Rock containing valuable minerals',
      ROE:          'Fish eggs',
      ROT:          'To decay',
      RUE:          'To feel regret',
      RUN:          'To move quickly on foot',
      CUE:          'A signal; a billiards stick',
      CUT:          'To divide with a sharp tool',
      CORN:         'A cereal grain; a hard patch of skin',
      CORE:         'The central part',
      CURE:         'To restore to health; a remedy',
      IRON:         'A metallic element; a clothes-pressing tool',
      NOTE:         'A record; a musical pitch',
      TOUR:         'A journey for pleasure',
      TRUE:         'Accurate; genuine',
      ROUT:         'A disorderly retreat; a crushing defeat',
      NURSE:        'A healthcare worker; to care for',
      CURSE:        'An invocation of harm; to swear',
      NOTICE:       'Awareness; a written announcement',
      RESURRECTION: 'In Mirandus, when a player character dies, they can be resurrected at Cemetery or Temple structures — the cost and speed of resurrection depends on the tier of the structure and the services of a Priest character',
    }
  },
]
