import type { Level } from '../types.js'

export const OCEAN_EVENT_LEVELS: Level[] = [
  {
    theme: 'WAVES', difficulty: 3.0,
    letters: ['W','A','V','E','S'],
    words: ['WAVES','AVES','SAVE','VASE','WAVE','AVE','AWE','SAE','SAW','SEA'], bonus: [],
    defs: {
      WAVES: 'Ridges of water travelling across the sea',
      AVES: 'Birds (taxonomic class)',
      SAVE: 'To rescue',
      VASE: 'A decorative vessel',
      WAVE: 'A wave',
      AVE: 'A greeting (Latin)',
      AWE: 'Reverent wonder',
      SAE: 'So (Scot.)',
      SAW: 'A word from the deep',
      SEA: 'A body of saltwater',
    }
  },
  {
    theme: 'CORAL', difficulty: 3.5,
    letters: ['C','O','R','A','L'],
    words: ['CAROL','CORAL','COLA','ORAL','ARC','CAR','COR','LAR','LOC','OAR'], bonus: ['CLARO'],
    defs: {
      CAROL: 'A song',
      CORAL: 'A reef-building marine organism — the foundation of ocean ecosystems',
      COLA: 'A cola drink',
      ORAL: 'Spoken',
      ARC: 'A curved line',
      CAR: '(dup)',
      COR: 'A word from the deep',
      LAR: 'A god',
      LOC: 'A word from the deep',
      OAR: 'A word from the deep',
      CLARO: 'A word from the deep',
    }
  },
  {
    theme: 'SHARK', difficulty: 4.0,
    letters: ['S','H','A','R','K'],
    words: ['SHARK','HARK','HAS','RAH','RAS','SAH','SHA','ASH','ARS','HARS'], bonus: ['KSAR'],
    defs: {
      SHARK: 'A cartilaginous predator — apex of many ocean food webs',
      HARK: 'To listen (arch.)',
      HAS: 'Owns',
      RAH: 'A cheer',
      RAS: 'A chief',
      SAH: '?',
      SHA: '?',
      ASH: 'A word from the deep',
      ARS: '?',
      HARS: 'A word from the deep',
      KSAR: 'A word from the deep',
    }
  },
  {
    theme: 'WHALE', difficulty: 4.5,
    letters: ['W','H','A','L','E'],
    words: ['WHALE','WHEAL','HALE','WALE','WEAL','HEAL','HEW','HAW','LAW','ALE','HAE','WAE','LAH'], bonus: [],
    defs: {
      WHALE: 'A massive marine mammal — the largest animals on Earth',
      WHEAL: 'A welt; a mound',
      HALE: 'Healthy',
      WALE: 'A welt (textile)',
      WEAL: 'Well-being',
      HEAL: 'A word from the deep',
      HEW: 'A word from the deep',
      HAW: 'A word from the deep',
      LAW: 'A rule',
      ALE: 'A beer',
      HAE: 'A word from the deep',
      WAE: 'A word from the deep',
      LAH: 'A word from the deep',
    }
  },
  {
    theme: 'ATOLL', difficulty: 5.0,
    letters: ['A','T','O','L','L'],
    words: ['ATOLL','TALL','ALTO','LOTA','TOLA','ALL','LOT','LAT','OAT','ALT','TAO'], bonus: ['LOTAL'],
    defs: {
      ATOLL: 'A ring-shaped coral reef enclosing a lagoon',
      TALL: 'High',
      ALTO: 'A vocal range',
      LOTA: 'A water vessel (India)',
      TOLA: 'A unit of mass',
      ALL: 'Every',
      LOT: 'A word from the deep',
      LAT: 'A muscle',
      OAT: 'A word from the deep',
      ALT: 'High pitch',
      TAO: 'A word from the deep',
      LOTAL: '?',
    }
  },
  {
    theme: 'KRAKEN', difficulty: 5.5,
    letters: ['K','R','A','K','E','N'],
    words: ['KRAKEN','RAKE','KNAR','NARK','RANK','KEN','RAN','ARK','ARE','EAR','EAN','ERA','ANE','NAE','REAK'], bonus: ['ANKER'],
    defs: {
      KRAKEN: 'A legendary sea monster of Scandinavian folklore',
      RAKE: 'A tool',
      KNAR: 'A knot in wood',
      NARK: 'An informer',
      RANK: 'A row',
      KEN: 'Knowledge',
      RAN: 'Past of run',
      ARK: 'A boat',
      ARE: 'Form of be',
      EAR: 'Hearing organ',
      EAN: 'A word from the deep',
      ERA: 'An age',
      ANE: 'A word from the deep',
      NAE: 'A word from the deep',
      REAK: 'A word from the deep',
      ANKER: 'A unit of liquid',
    }
  },
  {
    theme: 'LAGOON', difficulty: 6.0,
    letters: ['L','A','G','O','O','N'],
    words: ['LAGOON','ALONG','LOGON','GOAL','LOAN','LONG','GOO','LOG','NOG','GAL','GAN','GOA','NOO','LOO'], bonus: ['LOGAN'],
    defs: {
      LAGOON: 'A shallow body of water separated from a sea by a reef',
      ALONG: 'Beside',
      LOGON: 'A login',
      GOAL: '(dup)',
      LOAN: 'A loan',
      LONG: 'A word from the deep',
      GOO: 'Sticky',
      LOG: 'A log',
      NOG: 'A peg',
      GAL: 'A word from the deep',
      GAN: 'A word from the deep',
      GOA: 'A word from the deep',
      NOO: 'Now (Scot.)',
      LOO: '(dup)',
      LOGAN: '?',
    }
  },
  {
    theme: 'MARINER', difficulty: 7.0,
    letters: ['M','A','R','I','N','E','R'],
    words: ['MARINER','MARINE','REMAIN','RAMEN','AMIR','MAIN','MANE','MIEN','MINE','RAIN','RANI','REIN','AIM','AIN','AIR','ANE','ARE','ARM','EAR','ERA'], bonus: ['AIRMEN'],
    defs: {
      MARINER: 'A sailor; one who navigates the seas',
      MARINE: 'Of the sea',
      REMAIN: '(dup)',
      RAMEN: 'A word from the deep',
      AMIR: 'A Muslim ruler',
      MAIN: 'Principal',
      MANE: 'Animal hair',
      MIEN: 'Bearing',
      MINE: 'A word from the deep',
      RAIN: 'Precipitation',
      RANI: 'Indian queen',
      REIN: 'A bridle strap',
      AIM: 'To direct',
      AIN: 'Own (Scot.)',
      AIR: 'Atmosphere',
      ANE: 'A word from the deep',
      ARE: 'Form of be',
      ARM: 'A word from the deep',
      EAR: 'Hearing organ',
      ERA: 'An age',
      AIRMEN: 'A word from the deep',
    }
  },
  {
    theme: 'CURRENT', difficulty: 7.5,
    letters: ['C','U','R','R','E','N','T'],
    words: ['CURRENT','CRUET','CUTER','RECUT','TRUCE','TRUER','TUNER','CENT','CURE','CURT','RENT','RUNT','TERN','TRUE','TUNE','CUE','CUR','CUT','ERN','NET'], bonus: ['CURER'],
    defs: {
      CURRENT: 'A continuous flowing movement of water in the ocean',
      CRUET: '(dup)',
      CUTER: '(no I)',
      RECUT: '?',
      TRUCE: 'A ceasefire',
      TRUER: 'More true',
      TUNER: 'A tuner',
      CENT: 'A penny',
      CURE: 'A remedy',
      CURT: 'Brief',
      RENT: '(dup)',
      RUNT: 'A small one',
      TERN: 'A seabird',
      TRUE: 'Real',
      TUNE: '(dup)',
      CUE: 'A word from the deep',
      CUR: 'A word from the deep',
      CUT: 'A word from the deep',
      ERN: 'A word from the deep',
      NET: 'A mesh',
      CURER: 'A word from the deep',
    }
  },
  {
    theme: 'ATLANTIS', difficulty: 8.5,
    letters: ['A','T','L','A','N','T','I','S'],
    words: ['ATLANTIS','ATTAIN','ATLAS','LAINS','LATIN','NAILS','NATAL','SAINT','SATIN','SLANT','STAIN','STILT','TAILS','TILTS','TITAN','LAST','LIST','STAT','TILT','TINS'], bonus: ['ATTAINS'],
    defs: {
      ATLANTIS: 'The legendary lost island civilization — first described by Plato',
      ATTAIN: '(dup)',
      ATLAS: '(dup)',
      LAINS: 'A word from the deep',
      LATIN: '(dup)',
      NAILS: 'A word from the deep',
      NATAL: '(dup)',
      SAINT: '(dup)',
      SATIN: '(dup)',
      SLANT: '(dup)',
      STAIN: '(dup)',
      STILT: '(2 T)',
      TAILS: 'A word from the deep',
      TILTS: '(2 T)',
      TITAN: '(dup)',
      LAST: 'A word from the deep',
      LIST: 'A word from the deep',
      STAT: 'A statistic',
      TILT: 'A word from the deep',
      TINS: '(no extra)',
      ATTAINS: 'A word from the deep',
    }
  },
]
