import type { Level } from '../types.js'

export const TOWNSTAR_LEVELS: Level[] = [
  {
    theme: 'SILO', difficulty: 2.5,
    letters: ['S','I','L','O'],
    words: ['OIL','OILS','SILO'], bonus: ['SOIL'],
    defs: {
      OIL:  'A liquid fuel or lubricant — refined in Town Star\'s Refinery',
      OILS: 'Plural of oil; various liquid fuels',
      SILO: 'A tall cylindrical structure in Town Star used to store harvested crops like wheat and corn',
      SOIL: 'The ground material in which crops grow — also the currency in Common Ground World',
    }
  },
  {
    theme: 'FARM', difficulty: 2.8,
    letters: ['F','A','R','M'],
    words: ['FAR','RAM','MAR','FARM'], bonus: ['ARM'],
    defs: {
      FAR:  'At a great distance',
      RAM:  'A male sheep; also to push forcefully',
      MAR:  'To damage or spoil',
      FARM: 'The core production unit in Town Star — place crops and buildings to generate goods and earn Town Coin',
      ARM:  'A limb; to equip with tools or weapons',
    }
  },
  {
    theme: 'WHEAT', difficulty: 4.1,
    letters: ['W','H','E','A','T'],
    words: ['HAT','ATE','EAT','THE','HATE','HEAT','THAW','WHAT','WHEAT'], bonus: ['THEW'],
    defs: {
      HAT:   'A head covering',
      ATE:   'Past tense of eat',
      EAT:   'To consume food',
      THE:   'Definite article',
      HATE:  'Intense dislike',
      HEAT:  'Thermal energy; hot temperature',
      THAW:  'To melt or warm up from frozen',
      WHAT:  'Asking for clarification or identity',
      WHEAT: 'The key crop in Town Star — harvested from Wheat Fields to produce Flour at the Windmill and Bread at the Bakery',
      THEW:  'Physical strength or muscular bulk (archaic)',
    }
  },
  // 'WELL' level removed — letter pool (W,E,L,L) only supports 2 valid words
  // (ELL, WELL) which is below the MIN_WORDS_PER_LEVEL = 3 threshold. Reintroduce
  // by expanding the letter pool if this theme should return to rotation.
  {
    theme: 'TRACTOR', difficulty: 6.8,
    letters: ['T','R','A','C','T','O','R'],
    words: ['CAR','COT','OAR','OAT','ROT','TAR','CART','COAT','ROTA','ACTOR','TRACTOR'], bonus: ['ORCA'],
    defs: {
      CAR:     'A motor vehicle',
      COT:     'A small portable bed',
      OAR:     'A pole for rowing',
      OAT:     'A grain crop',
      ROT:     'To decay; nonsense (informal)',
      TAR:     'A dark sticky substance',
      CART:    'A two-wheeled vehicle; to carry goods',
      COAT:    'An outer garment; a layer of material',
      ROTA:    'A list of duties on rotation',
      ACTOR:   'A performer in a play or film',
      TRACTOR: 'The Farm Tractor in Town Star is a vehicle NFT that speeds up nearby crop and farm operations, boosting production output significantly',
      ORCA:    'A type of killer whale',
    }
  },
  {
    theme: 'WINDMILL', difficulty: 8.2,
    letters: ['W','I','N','D','M','I','L','L'],
    words: ['DIM','ILL','MID','MIL','WIN','DILL','MILD','MILL','MIND','WILD','WILL','WIND','WINDMILL'], bonus: ['LIMN'],
    defs: {
      DIM:      'Not bright; to reduce light',
      ILL:      'Sick or unwell',
      MID:      'In the middle of',
      MIL:      'A unit of measurement (thousandth of an inch)',
      WIN:      'To succeed or achieve victory',
      DILL:     'An aromatic herb used in cooking',
      MILD:     'Gentle; not extreme',
      MILL:     'A machine for grinding; a processing facility',
      MIND:     'The intellect; to object to something',
      WILD:     'Uncontrolled; found in nature',
      WILL:     'Determination; future tense auxiliary',
      WIND:     'Moving air; to coil or wrap',
      WINDMILL: 'A core power structure in Town Star — converts wind to energy, powering surrounding buildings without fuel costs',
      LIMN:     'To draw or paint; to depict (archaic)',
    }
  },
  {
    theme: 'BAKERY', difficulty: 6.5,
    letters: ['B','A','K','E','R','Y'],
    words: ['ARK','BAR','BAY','EAR','ERA','RYE','BARE','BARK','BRAY','RAKE','YEAR','BAKER','BAKERY'], bonus: ['BYRE'],
    defs: {
      ARK:    'A large boat; a place of refuge',
      BAR:    'A rod; a drinking establishment; to block',
      BAY:    'A body of water; a laurel tree; to howl',
      EAR:    'The organ of hearing',
      ERA:    'A long period of history',
      RYE:    'A cereal grain used in bread and whiskey',
      BARE:   'Uncovered; minimal',
      BARK:   'The outer layer of a tree; a dog\'s sound',
      BRAY:   'The sound of a donkey; to crush or grind',
      RAKE:   'A garden tool; to gather or search through',
      YEAR:   'A 12-month period',
      BAKER:  'One who bakes bread and pastries',
      BAKERY: 'In Town Star, the Bakery converts Flour and Butter into Baguettes and Bread — high-value crafted goods for earning Town Coin',
      BYRE:   'A cowshed or barn (British dialect)',
    }
  },
  {
    theme: 'LUMBER', difficulty: 5.5,
    letters: ['L','U','M','B','E','R'],
    words: ['BUR','EMU','RUB','RUE','RUM','BLUR','BURL','RULE','RUBLE','LUMBER'], bonus: [],
    defs: {
      BUR:    'A rough prickly seed casing; a rough edge left by a drill',
      EMU:    'A large flightless Australian bird',
      RUB:    'To apply friction; to polish',
      RUE:    'To feel regret; a bitter herb',
      RUM:    'An alcoholic spirit made from sugarcane',
      BLUR:   'An unclear image; to make indistinct',
      BURL:   'A rounded knotty growth on a tree',
      RULE:   'A regulation; to govern',
      RUBLE:  'The currency of Russia',
      LUMBER: 'In Town Star, Lumber is produced by the Lumber Mill from Wood — an essential material for building and crafting Wooden Boxes and other goods',
    }
  },
  {
    theme: 'STORAGE', difficulty: 9.8,
    letters: ['S','T','O','R','A','G','E'],
    words: ['STORAGE','GROAT','STORE','GATE','GOAT','GORE','OAST','ROTE','SAGE','SORT','STAG','STAR','AGE','ATE','EAR','EAT','ERA','GAS'], bonus: [],
    defs: {
      AGE:     'A period of time; to grow older',
      ATE:     'Past tense of eat',
      EAR:     'The organ of hearing',
      EAT:     'To consume food',
      ERA:     'A long period of history',
      GAS:     'A fuel; a state of matter',
      GOT:     'Past tense of get',
      OAR:     'A rowing pole',
      ORE:     'Rock containing valuable minerals',
      ROE:     'Fish eggs',
      ROT:     'To decay',
      SAT:     'Past tense of sit',
      TAR:     'A dark sticky liquid',
      TOE:     'A digit on the foot',
      GATE:    'An entry point; to restrict access',
      GOAT:    'A horned animal; one who takes blame',
      GORE:    'Blood from a wound; to pierce',
      OAST:    'A kiln for drying hops or malt',
      ROTE:    'Learning by repetition without understanding',
      SAGE:    'A wise person; an aromatic herb',
      SORT:    'A type or kind; to arrange',
      STAR:    'A celestial body; a celebrity',
      STAG:    'A male deer; a party for men only',
      STORE:   'A shop; to keep goods',
      GROAT:   'A small historical coin',
      STORAGE: 'In Town Star, Storage buildings like the Silo, Storehouse, and Warehouse hold your crafted goods and raw materials — running out of storage halts production',
    }
  },
  {
    theme: 'PASTURE', difficulty: 9.2,
    letters: ['P','A','S','T','U','R','E'],
    words: ['PASTURE','PAUSE','PURSE','SUPER','TAPER','APES','PAST','PEAT','PURE','RATE','REAP','RUSE','SPAR','SPAT','APE','ART','EAR','EAT','ERA'], bonus: ['UPSET'],
    defs: {
      APE:     'A large primate; to imitate',
      ART:     'Creative expression',
      EAR:     'The organ of hearing',
      EAT:     'To consume food',
      ERA:     'A long period of time',
      PET:     'A domesticated animal; to stroke gently',
      RUE:     'To regret; a bitter herb',
      RUT:     'A groove worn by wheels; a fixed routine',
      SAP:     'Tree fluid; to drain energy from',
      SAT:     'Past tense of sit',
      TAR:     'A dark sticky substance',
      APES:    'Plural of ape; mimics',
      PAST:    'Earlier time; beyond',
      PEAT:    'Decomposed vegetation used as fuel',
      PURE:    'Free from contamination; unmixed',
      RATE:    'A measure of speed or frequency; to evaluate',
      REAP:    'To harvest crops',
      RUSE:    'A trick or deception',
      SPAR:    'To fight lightly; a boxing match',
      SPAT:    'A minor quarrel; past tense of spit',
      PURSE:   'A bag for carrying money',
      SUPER:   'Excellent; above',
      TAPER:   'To narrow gradually; a thin candle',
      PAUSE:   'A brief stop or rest',
      PASTURE: 'In Town Star, Pasture terrain is required for livestock buildings like Sheep Pens and Milk Barns — animals need grassy land to graze on',
      UPSET:   'To disturb; to overturn; a surprising defeat',
    }
  },
  {
    theme: 'GASOLINE', difficulty: 11.5,
    letters: ['G','A','S','O','L','I','N','E'],
    words: ['GASOLINE','SINGLE','SLOGAN','GAIN','GALE','GOAL','LANE','LEAN','LIEN','LINE','LION','LOAN','LONE','LONG','LOSE','NAIL','SALE','SEAL','SIGN','SINE'], bonus: ['LEGIONS'],
    defs: {
      AGE:      'A period of time',
      ALE:      'A type of beer',
      GALE:     'A strong wind',
      GAIN:     'To obtain; an increase',
      LANE:     'A narrow road or division of a road',
      LEAN:     'Thin; to incline',
      LIEN:     'A legal claim on property',
      LINE:     'A straight mark; a queue',
      LION:     'A large African cat',
      LONE:     'Solitary; alone',
      LOSE:     'To be defeated; to misplace',
      NAIL:     'A metal fastener; to secure',
      GOAL:     'An objective; a score in sport',
      SIGN:     'A symbol or notice; to write one\'s name',
      SALE:     'An act of selling',
      SEAL:     'A marine mammal; to close securely',
      SINE:     'A trigonometric function',
      SOLE:     'The underside of a foot or shoe; alone',
      SONG:     'A piece of music with words',
      LONG:     'Extended in length; to yearn for',
      LOAN:     'Money lent with expectation of repayment',
      SINGLE:   'One; unmarried; a baseball hit',
      SLOGAN:   'A memorable phrase used in advertising',
      GASOLINE: 'The most critical resource in Town Star — produced at the Refinery from Oil, Gasoline fuels vehicles and is required for production operations across your town',
      LEGIONS:  'Large groups; multitudes',
    }
  },
  {
    theme: 'TERRAIN', difficulty: 8.8,
    letters: ['T','E','R','R','A','I','N'],
    words: ['ANT','ART','EAR','ERA','IRE','NET','NIT','TAN','TAR','TEN','EARN','RANT','RAIN','REIN','RENT','TIER','TIRE','TRAIN','TERRAIN'], bonus: ['INERT'],
    defs: {
      ANT:     'A small insect that lives in colonies',
      ART:     'Creative expression',
      EAR:     'The organ of hearing',
      ERA:     'A long period of history',
      IRE:     'Anger or wrath',
      NET:     'A mesh; remaining after deductions',
      NIT:     'A louse egg; to pick faults',
      TAN:     'A light brown color; to cure leather',
      TAR:     'A dark sticky substance',
      TEN:     'The number 10',
      EARN:    'To receive payment for work',
      RANT:    'To speak angrily at length',
      RAIN:    'Water falling from clouds',
      REIN:    'A strap to control a horse; to restrain',
      RENT:    'Payment for use; a tear',
      TIER:    'A level or rank',
      TIRE:    'To grow weary; a rubber wheel covering',
      TRAIN:   'A series of linked vehicles; to instruct',
      TERRAIN: 'In Town Star, the map has six terrain types — Desert, Forest, Ice, Mountain, Ocean, and Plains — each affects which crops grow and which buildings you can place',
      INERT:   'Lacking motion or chemical activity',
    }
  },
  {
    theme: 'REFINERY', difficulty: 10.5,
    letters: ['R','E','F','I','N','E','R','Y'],
    words: ['FRY','IRE','RYE','FERN','FIRE','FINE','REIN','RIFE','FIERY','FINERY','REFINE','REFINERY'], bonus: [],
    defs: {
      FRY:      'To cook in hot oil; a young fish',
      IRE:      'Anger or wrath',
      RYE:      'A cereal grain used in bread and whiskey',
      FERN:     'A leafy non-flowering plant',
      FIRE:     'Combustion; to dismiss from a job',
      FINE:     'Of high quality; a monetary penalty',
      REIN:     'A strap to control a horse',
      RIFE:     'Widespread; full of',
      FIERY:    'Consisting of or resembling fire; passionate',
      FINERY:   'Showy clothes and accessories',
      REFINE:   'To purify; to improve',
      REFINERY: 'The industrial heart of Town Star — the Refinery processes Oil into Gasoline, which is required to run most town operations and vehicles',
    }
  },
  {
    theme: 'HARVEST', difficulty: 11.8,
    letters: ['H','A','R','V','E','S','T'],
    words: ['HARVEST','STARVE','EARTH','HASTE','HEART','STAVE','HARE','HART','HATE','HAVE','HEAT','RATE','RAVE','SAVE','STAR','ARE','ART','EAR','ERA','HAS'], bonus: ['AVERTS'],
    defs: {
      ARE:     'Second person singular of "be"',
      ART:     'Creative expression',
      EAR:     'The organ of hearing; seed-bearing spike of a grain plant',
      ERA:     'A long period of history',
      HAS:     'Third person singular of "have"',
      HAT:     'A head covering',
      HER:     'Belonging to a female person',
      SAT:     'Past tense of sit',
      SET:     'A collection; to place',
      TAR:     'A dark sticky substance',
      THE:     'Definite article',
      HAVE:    'To possess',
      HATE:    'Intense dislike',
      HEAT:    'Thermal energy',
      HARE:    'A fast-running mammal like a large rabbit',
      HART:    'An adult male deer (archaic)',
      RAVE:    'To talk wildly; an all-night dance party',
      RATE:    'A measure or speed; to evaluate',
      SAVE:    'To rescue; to preserve',
      STAR:    'A celestial body; a celebrity',
      STAVE:   'A staff; to break inward; to postpone',
      EARTH:   'Soil; the planet',
      HASTE:   'Speed; urgency',
      HEART:   'The organ that pumps blood; the emotional center',
      STARVE:  'To suffer from lack of food',
      HARVEST: 'The act of collecting mature crops — in Town Star, harvesting fields at the right time is key to maintaining a productive and profitable town',
      AVERTS:  'Prevents; turns away',
    }
  },
  {
    theme: 'PROXIMITY', difficulty: 12.5,
    letters: ['P','R','O','X','I','M','I','T','Y'],
    words: ['MIX','OPT','POI','POX','PRY','RIM','ROT','TIP','TOP','TRIM','MIRY','PIXY','PRIVY','PROXY','IMPORT','PROXIMITY'], bonus: ['TORPID'],
    defs: {
      MIX:       'To combine or blend',
      OPT:       'To choose',
      POI:       'A Hawaiian food made from taro root',
      POX:       'A disease causing skin eruptions',
      PRY:       'To inquire nosily; to lever open',
      RIM:       'The outer edge',
      ROT:       'To decay',
      TIP:       'The pointed end; a gratuity; a piece of advice',
      TOP:       'The highest point',
      TRIM:      'To cut neatly',
      MIRY:      'Boggy; covered in mud',
      PIXY:      'A playful fairy (variant of pixie)',
      PRIVY:     'Private; aware of a secret',
      PROXY:     'A substitute; an agent authorized to act for another',
      IMPORT:    'To bring in from abroad; significance',
      PROXIMITY: 'In Town Star, Proximity Effects are a core game mechanic — placing buildings near compatible ones grants production bonuses, while placing polluting buildings near homes reduces their output',
      TORPID:    'Mentally or physically inactive; dormant',
    }
  },
]
